### ISSUE TITLE
Autograding should be a job

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#1003]
Autograding all final submissions can be a background job. This job can watch for scores getting posted back and report its progress.

* The final submissions query won't timeout the request
* We can report progress on autograding, instead of using the autograder RQ interface
* We can retry submissions that did not get scores after some timeout (#1002)

**Comment by Sumukh** [comment]
The current workflow for most people was just wait for a while and see what happens 

Providing visibility about what's going on would be great. How do you think we can get scores posted back? A query for recent scores on the assignment?

**Comment by knrafto** [comment]
That could work. Another approach would be to generate an "autograder job ID" (this could just be the Ok job ID) and give that to the autograder. The autograder would gives this back to Ok when it posts a score, and we can query for scores for this job ID.

**Comment by Sumukh** [comment]
Resolved by #1066
