### ISSUE TITLE
Score Audit Log

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#1007]
Having a score audit log for all assignments (and on an assignment by assignment basis) can be useful. 

- Audit log to review changes that instructors are making
- Quick way to glance at the distribution of scores.

**Comment by knrafto** [comment]
You mean some kind of interface to view changes to scores? What short of information should we display on that interface?

I agree that a distribution of scores is useful, but I'd like to spin that off into a separate issue.

**Comment by Sumukh** [comment]
I was thinking this would just be a table of scores sorted by recently created. 

Re: Distribution - a graph would be nice but I think a list of scores accomplishes what we want to do. Often after an autograding run - you just want to see how the results looked.

**Comment by knrafto** [comment]
I think a distribution is useful - right now we just have an average (in metabase). And in CS 168, many students have been requesting project distributions since the class is curved.
