### ISSUE TITLE
Strip spaces from fields in enrollment from CSV

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#1010]
Just had a case where a student didn't get scores on bCourses because they had a space after their SID.

**Comment by Sumukh** [comment]
Forms are supposed to strip whitespace for text fields by default thanks to https://github.com/Cal-CS-61A-Staff/ok/blob/master/server/forms.py#L120 - not sure how that happened.

**Comment by knrafto** [comment]
CSV most likely? Updated the title.

**Comment by Sumukh** [comment]
These are the lines that we should look at: https://github.com/Cal-CS-61A-Staff/ok/blob/master/server/models.py#L854

Should be as simple as doing a `.strip()`
