### ISSUE TITLE
Jobs should store return value

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#1014]
The return value can provide a summary or something more useful than the log. 

MOSS: Returns a one line string for the MOSS url (instead of having to scroll through the log to find it) 
(Future) Export Jobs: Returns a link to the file url 
bCourses Jobs: Returns a summary of changes ("15 grades changed") 

Bonus: It would be great if our jobs could output HTML so we could render tables etc. 

Proposed solution. 

Add a parameter to the job field (and the job schema) to store what kind of output we are expecting. 
Add a MEDIUMTEXT field (16 MiB) to the job schema store the output of the job. 

Render the return value above the log. 

```
enqueue_job(..., result_format='link') 
enqueue_job(..., result_format='string')
enqueue_job(..., result_format='html') 
```

**Comment by knrafto** [comment]
Since a string is HTML, and a link could be an `<a>` tag, why not make the result always HTML?

**Comment by Sumukh** [comment]
I mainly wanted a type to control how we display the result in this table: 

![image](https://cloud.githubusercontent.com/assets/882381/21491572/9ac9c9f2-cbb2-11e6-96b7-249e60569717.png)

It's hard to tell from a just a string if we can render a button or not.
