### ISSUE TITLE
OAuth page takes up too much space

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#1020]
Here's how it looks on my 13-inch laptop:
<img width="1280" alt="screen shot 2016-12-27 at 12 04 22 am" src="https://cloud.githubusercontent.com/assets/2042019/21494692/127f844a-cbc8-11e6-969f-8b77fe8fa59b.png">

I have to scroll to see the "confirm" button. It should easily fit on one page so I don't have to scroll. In particular, there's a lot of empty space at the top (probably because some of the CSS is shared with the landing page CSS).

**Comment by Sumukh** [comment]
I tried removing some of it with  https://github.com/Cal-CS-61A-Staff/ok/commit/2e8d415a2dc6e5b713aee41b898fdb20524faf4d - but I did not go far enough because I didn't make a new base template. 

It'll be much easier once there is a new base template for the OAuth view.
