### ISSUE TITLE
Bundle external JS/CSS dependencies with webassets

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#1036]
`webassets` is a great way to bundle all of our JS assets, but it doesn't handle external URLs well. We should be able to configure it with a URL, so that `webassets` can just pull from the URL once (on first request in dev, and when we build the docker image for prod).

`bower` also solves this problem but we'd like to avoid introducing an npm/bower dependency. It also grabs the entire repo, instead of just the released JS/CSS file directly.

**Comment by Sumukh** [comment]
Resolved by #1037
