### ISSUE TITLE
Automatically grade on "effort"

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#1044]
@PNHilfinger: "It would be nice if OK could somehow notice effort as well as correctness."

I'm not sure if this is OK's job or the autograder's, but it seems like a difficult problem.

**Comment by colinschoen** [comment]
Perhaps do we look at the difference in number of lines changed from the average of correct solutions and set some relative threshold?

**Comment by Sumukh** [comment]
A good first attempt might be a job that gives credit to all submission _if_ the submission is X lines different from the solution. 

(the amount of points and number of lines can be configured by the staff member). @colinschoen - are you interested in this?

**Comment by colinschoen** [comment]
Sure. To clarify:

If X lines different from the solution referring to the quantity or the content?

**Comment by Sumukh** [comment]
quantity - instead of differing from the solution - how about from the template instead. There are obvious ways to game that - but I'm interested in seeing if it addresses most of what instructors are after.

**Comment by epai** [comment]
Made a first attempt in #1167
