### ISSUE TITLE
Add Label for Grading Types that Override Autograder Type

### ISSUE THREAD

**Issue by colinschoen** [Cal-CS-61A-Staff/ok#1074]
It isn't clear which grading types override the autograder grades. It would be nice if a label or some hint was given in the select.

**Comment by knrafto** [comment]
OK tries not to be opinionated on what the grade kinds actually mean (although the list of kinds is hardcoded). It's up to whoever processes the grades, either a human or the bCourses export config

**Comment by colinschoen** [comment]
Makes sense. I was under the impression that the grading type priorities were something built into `OK`. Closing.
