### ISSUE TITLE
Indicate if submission was made by staff in admin view

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#1075]
The admin panel does not indicate if a submission was made by staff - so it can be confusing if you create an upload through the staff dashboard and it's not obvious that your upload was successful (in the table). 

Files to change: https://github.com/Cal-CS-61A-Staff/ok/blob/master/server/templates/staff/student/assignment.html#L212 (edited)

What to change: you'd probably just change that line in the template to have an if block that says `if backup.creator` -> staff@example.org on behalf of student@example.com  `else` student@example.com

reported by: @kavigupta

**Comment by Konstantinov-Innokentii** [comment]
Hi, i want to help fix this issue, from what should i start?
