### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by MrVantastic** [Cal-CS-61A-Staff/ok#1097]
I am trying to install Ok but when I try to install the required packages in requirements.txt, I keep running into this error: 

`Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/k1/wbn710jd36d88fcp84z11lv80000gn/T/pip-build-jcfs4hlx/lockfile/`

I've found that if I delete the line `lockfile==0.10.2 # For local storage` from requirements.txt and run 
`pip install -r requirements.txt`, it works just fine. 

I've tried googling the problem, and I found [this](http://stackoverflow.com/questions/35991403/python-pip-install-gives-command-python-setup-py-egg-info-failed-with-error-c): 

> Error code 1 is defined in errno.h and means Operation not permitted.

The suggested solution was to use the command `pip install --upgrade setuptools` but I'm still running into the same error. 

I was wondering, would it be possible to install lockfile [separately](https://pypi.python.org/pypi/lockfile/0.10.2#downloads) and just delete that line? Or is there a better fix?

**Comment by Sumukh** [comment]
Sure. Are you running the command inside of a virtualenv? 

This isn't a good solution - but does `sudo pip install lockfile` resolve it? 

If you end up not being able to install lockfile that's fine - you should still be able to work on non-file related things by doing the following: 

Change line 23 of dev.py to 
`STORAGE_PROVIDER = os.environ.get('STORAGE_PROVIDER',  'DUMMY')` 

and add the following lines to storage.py (in init_app  - after line 62 - right before the get_container call ) 

```
        if self.provider == Provider.DUMMY:
            self.driver.create_container(container_name=self.container_name)
```

**Comment by MrVantastic** [comment]
I just tried running the command from the outside of a virtualenv and it seems to have worked. If it turns out I'm supposed to have run the command inside of a virtualenv, I'll try the solution you mentioned. 

Thank you so much!
