### ISSUE TITLE
Better "View Revision" Link

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#1140]
It's not very clear that a revision has been submitted 

Also the spacing is off for the current link:

![image](https://cloud.githubusercontent.com/assets/882381/25200327/cad4339a-2502-11e7-81da-4c9eaf1da7e5.png)

It might be worth it to add a table just for revisions.

**Comment by addcninblue** [comment]
Hello! I'm new to contributing, so I'm looking for a small good-for-first-timers contribution.
Is there anything wrong with putting the "View Composition Revision" on a new line to allow for better visibility?

Something like this:
![image](https://user-images.githubusercontent.com/7519521/34064914-bd5c2198-e1b1-11e7-903e-806d7b8de9d6.png)

**Comment by Sumukh** [comment]
@addcninblue Seems like a good idea! I think we previously hadn't done that because it messed up the design a little bit (the height of the box would be uneven) - but I don't think that's a huge problem.

**Comment by addcninblue** [comment]
I'm currently trying to test the code, but I'm not quite sure how to force the assignments to have composition revisions. I assumed that [line 341 from ok/generate.py](https://github.com/Cal-CS-61A-Staff/ok/blob/master/server/generate.py#L341) would generate the compositions, but changing the block to always run doesn't seem to work.

Besides that, I have the code [here](https://github.com/addcninblue/ok/commit/9451a576650e52e41fa8e3b0ea3d005847dd7f7b), where I added a `<br>` tag for newline.

**Comment by Sumukh** [comment]
I think you need to add a score tag called revision or something like that. I'd search the codebase for revision to see the details of how that happens.

**Comment by epai** [comment]
Resolved by #1220.  Thanks for the quick fix @addcninblue!
