### ISSUE TITLE
Allow students to sign-up with non-gmail emails

### ISSUE THREAD

**Issue by epai** [Cal-CS-61A-Staff/ok#1155]
A few clients from outside of Berkeley want to use OK, but for legal/logistical reasons cannot use gmail accounts.  

Is there any reason why we require gmail emails besides the fact that we use google auth?

**Comment by colinschoen** [comment]
We don't. You can use an email with any domain as long as it is a Google Account.

**Comment by epai** [comment]
Wait, what's considered a "Google Account"?  Can you create one without using gmail?

**Comment by colinschoen** [comment]
Sure

https://accounts.google.com/SignUp

Just click `I prefer to use my current email address`

Also any gsuite organization's domains count as well (e.g. @berkeley.edu).

**Comment by epai** [comment]
Awesome - I didn't know you can do that.  Thanks Colin!

**Comment by colinschoen** [comment]
Sure thing :)
