### ISSUE TITLE
Handle issues gracefully on the frontend.

### ISSUE THREAD

**Issue by moowiz** [Cal-CS-61A-Staff/ok#116]
Right now, when the API errors on the front end, the exception is swallowed up. 

We should show this to the user.

**Comment by alvinwan** [comment]
Error messages are now accessible with err.data.message (or response.data.message).

Here's an example of error message being passed successfully.

![error-messages-fix](https://cloud.githubusercontent.com/assets/2068077/8505272/675c384c-2196-11e5-81da-415542ada95f.gif)
