### ISSUE TITLE
Cannot access /rq/ when admin, 3 failed tests

### ISSUE THREAD

**Issue by Carouelle** [Cal-CS-61A-Staff/ok#1188]
I was trying out the project locally. 

Trying to access /rq/ as admin throws an error 500.
Subsequently, 3 of the tests fail, one of them explicitely accessing /rq/.
Failing tests:
- test_dashboard_access
- test_failing_job
- test_job

Researching the error on Google, it turns out I needed to install the redis-server package. After doing so, /rq/ was accessible and all tests passed.

So I am submitting a PR adding this as an instruction to the readme.

**Comment by Sumukh** [comment]
:+1: Seems like a good idea

**Comment by Sumukh** [comment]
Merged
