### ISSUE TITLE
Support for R?

### ISSUE THREAD

**Issue by terhorst** [Cal-CS-61A-Staff/ok#1209]
Can you describe would be modifications would be needed to support assignments in the R programming language?

**Comment by jathak** [comment]
The Ok submission server (this project) should be language agnostic, provided code can be submitted as plain text files.

The autograder should also be language agnostic, provided you can set it up to run in a Docker environment ([see here](https://okpy.github.io/documentation/autograder.html)).

The [Ok client](https://github.com/Cal-CS-61A-Staff/ok-client) is Python-based, and is currently focused only on the languages used by CS 61A (Python, a Python-based Scheme interpreter, and SQLite).
