### ISSUE TITLE
Autograder code?

### ISSUE THREAD

**Issue by yuvipanda** [Cal-CS-61A-Staff/ok#1213]
Heya! I'm wondering if the autograder code is also open source? https://okpy.github.io/documentation/autograder.html makes no mention of it, and I can't find 'autopy' anywhere else online.

Thanks!

**Comment by yuvipanda** [comment]
Mostly interested in the code that is handling the POST from https://github.com/Cal-CS-61A-Staff/ok/blob/master/server/autograder.py#L71

**Comment by colinschoen** [comment]
Hi Yuvi,

It isn't, but you can get access to the service by emailing sumukh@berkeley.edu
