### ISSUE TITLE
Disable OK prompt for "Run only this test case"

### ISSUE THREAD

**Issue by jerryjrchen** [Cal-CS-61A-Staff/ok#1226]
It's currently buggy, so it's misleading to display this information to students.
![screen shot 2018-01-23 at 20 37 52](https://user-images.githubusercontent.com/8547284/35314823-7c789b12-007d-11e8-92fb-12474b1aa7eb.png)

**Comment by colinschoen** [comment]
Please create an issue here: https://github.com/Cal-CS-61A-Staff/ok-client

This is an OK-Client issue.
