### ISSUE TITLE
Scheme interpreter used in ok tests displays booleans incorrectly

### ISSUE THREAD

**Issue by tmmydngyn** [Cal-CS-61A-Staff/ok#1238]
ok's Scheme interpreter outputs `True`/`False` instead of `#t`/`#f`. It seems that the Scheme interpreter included in the zip file outputs `#t`/`#f` like we want, so not really sure what's going on here.

WWSD example:
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
What Would Scheme Print? > Suite 1 > Case 10

scm> (equal? '(1 . (2 . 3)) (cons 1 (cons 2 (cons 3 nil))))  ; Recall how boolean values are displayed
False

# Error: expected
#     #f
# but got
#     False
```

Code writing example (where I wrote `over-or-under` to return `#t`, this test doesn't expect `#t` but just using it to show how it would get output anyway):
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
over-or-under > Suite 1 > Case 1

scm> (load 'lab09)

scm> (load 'lab09_extra)

scm> (over-or-under 5 5)
True

# Error: expected
#     0
# but got
#     True
```

**Comment by jathak** [comment]
I just checked the ok-client code, and it's definitely loading tests from the interpreter that's included in the zip. I think it's possible that our interpreter is properly displaying booleans when outputting, but isn't properly doing so when called programmatically by the ok-client. Looking into it now

**Comment by jathak** [comment]
Found the bug. ok-client has two options for testing Scheme: `ok_test/scheme` and `scheme_test`. `scheme_test` is built on top of the repl, so it works fine, but `ok_test/scheme` is getting the raw value, not just output, so it doesn't work. Working on a fix in ok-client now

**Comment by jathak** [comment]
This issue was moved to Cal-CS-61A-Staff/ok-client#342
