### ISSUE TITLE
Refactor to support Flask 0.12.3

### ISSUE THREAD

**Issue by colinschoen** [Cal-CS-61A-Staff/ok#1253]
Flask 0.12.3 is breaking the build per #1252. Changes to fix this will likely involve our use of the `Request.get_json()` method.

**Comment by davidism** [comment]
I released 0.12.4 to fix this.

**Comment by colinschoen** [comment]
Thanks for the personal attention on this, @davidism. I'll remove fixed version dependency for flask now.
