### ISSUE TITLE
Set up HTTPS for okpy.org

### ISSUE THREAD

**Issue by sharadmv** [Cal-CS-61A-Staff/ok#151]
I think we should have HTTPS for okpy.org at some point.

I think it's pretty annoying, but I'm somewhat familiar with setting up SSL, and I think I need access to wherever the domain was bought from.

Any ideas on how to get started?

Here's a guide from Google: https://developers.google.com/appengine/docs/domain

**Comment by Sumukh** [comment]
A ticket to IST revealed that the IPv6 DNS config for okpy.org is incorrect. This would be why Airbears2 always revealed SSL failures or just failed for okpy.org. (Airbears just uses IPv4) - @papajohn can you remove the AAAA records for okpy.org ?

**Comment by papajohn** [comment]
AAAA records removed.
