### ISSUE TITLE
Non-English Computer Names break server connections

### ISSUE THREAD

**Issue by soumyabasu** [Cal-CS-61A-Staff/ok#182]
If the computer name is in a different language (specific case was in Korean), the server connection breaks and gives an error saying that 'utf-8 codec can't decode byte 0xc7 in position 0; invalid continuation byte'. The problem was fixed by changing the computer name to English.

This is a problem in Python and most fixes I saw required changing stuff in Python's given files.

Relevant StackOverflow link: https://stackoverflow.com/questions/23109244/unicodedecodeerror-with-runserver.

I'm really not sure what to do here. Does anyone have any ideas?

**Comment by papajohn** [comment]
Client issue. Closing.
