### ISSUE TITLE
Do "smart" dumping of tests

### ISSUE THREAD

**Issue by albert12132** [Cal-CS-61A-Staff/ok#229]
* The client currently writes to every single test file regardless of whether or not they have changed. Add a "modified" attribute to each serilizable object and only right to files that contain modified objects.
* Safely dump files -- right now if an error occurs in ok_main, test files might get corrupted
* Add a --no-save flag to choose never to dump, even if tests are modified

**Comment by papajohn** [comment]
Test dumping works fine.
