### ISSUE TITLE
okpy.org doesn't work

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/ok#236]
When I try to connect to okpy.org, I get an SSL error. Perhaps the easiest fix is to just have okpy.org be a separate server that serves a redirect to ok-server.appengine.com. I believe we can't yet support SSL for a custom domain. (We don't have a Google Apps account, and I strongly dislike the idea of setting one up. https://cloud.google.com/appengine/docs/ssl )

Other ideas?

**Comment by Sumukh** [comment]
A ticket to IST revealed that okpy.org has an invalid IPv6 config. @papajohn - The fix is to delete the AAAA records in the DNS for okpy.org. 

(This is why it worked on Airbears which can only do IPv4 but not AirBears2)
