### ISSUE TITLE
Add course enrollment info to auth page

### ISSUE THREAD

**Issue by sharadmv** [Cal-CS-61A-Staff/ok#24]
Right now, the auth page redirects to a really simple HTML page that basically says "You have successfully authenticated".

Ideally it'll look prettier :).

**Comment by papajohn** [comment]
In particular, it would be nice if the auth page showed course enrollment information to verify that the correct account was used.

**Comment by alvinwan** [comment]
@papajohn It looks like the simple auth page "You have successfully authenticated" was removed sometime between then and now. Should we restore that page/functionality to display the course information?

**Comment by papajohn** [comment]
Right now, I do see "Ok! You have successfully authenticated" when I log
in. I think it should also show the courses in which you're currently
enrolled. If you're not enrolled in any course, it should say: "Warning:
you are not enrolled in any course with the email address <email>. You
should contact your instructor or log in with another account."

**Comment by alvinwan** [comment]
@papajohn I see. That makes sense. Although, I'm unable to get to the authentication page; am I doing something wrong? 

Instead, it redirects me right to the courses page (gif below):
![site-user-flow](https://cloud.githubusercontent.com/assets/2068077/7895072/8a645d74-062f-11e5-87d4-17ba087ff0d5.gif)

**Comment by albert12132** [comment]
I think John is referring to the ok-client auth page (the page that shows
up when students authenticate from the command line).

**Comment by alvinwan** [comment]
Aha. Sumukh just explained it to me. My mistake.

**Comment by alvinwan** [comment]
Completed. Both components -- for ok-client and for ok -- are under the branch name "enh/24/auth".

@Sumukh Could you review these changes? I fed both the client and the server seed data, when I was testing. Made a PR on ok-client as well.

Ok-client:
- new HTML templates for the page
- assets are loaded from server
- enrollment information loaded via API

Ok server:
- API for enrollment information `/enrollment?email=[email]`.

When the user is not enrolled in courses:

![site-auth-empty](https://cloud.githubusercontent.com/assets/2068077/7896005/1ac52d92-065f-11e5-8510-3901d1320bd4.gif)

When the user is enrolled in courses:

![site-auth-filled](https://cloud.githubusercontent.com/assets/2068077/7896013/548ab6dc-065f-11e5-97f5-eb69ab874943.gif)

**Comment by soumyabasu** [comment]
Fantastic work! :)

Two comments:

1- Right now, enrollment works by auto-enrolling any student that submits an assignment for a course. This isn't the right long-term solution (there should be a class roster and only those students can submit). So, we need some backend changes to be made in your PR as well.

2- The branch should have been named something like enhancement/alvinwan/auth (or bug/alvinwan/auth), but that's entirely my bad- there should be documentation on this repo which I'll add by the end of the weekend.

**Comment by alvinwan** [comment]
Thanks!

1. I see. I'll fiddle with it tomorrow.

2. My bad. I just thought it was weird putting my name in all the branch names. x)

**Comment by alvinwan** [comment]
@soumyabasu Should I work on adding an admin interface for managing enrollment (a simple CSV of all registered emails), or try to devise some clever way of checking without auto-enrolling?

**Comment by soumyabasu** [comment]
We need an admin interface- auto enrollment won't work in the long run

On Tuesday, June 16, 2015, Alvin Wan <notifications@github.com> wrote:

> @soumyabasu <https://github.com/soumyabasu> Should I work on adding an
> admin interface for managing enrollment (a simple CSV of all registered
> emails), or try to devise some clever way of checking without
> auto-enrolling?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Cal-CS-61A-Staff/ok/issues/24#issuecomment-112336346>.
>


-- 
Sent from Phone

**Comment by alvinwan** [comment]
You can now enroll and unenroll students. You can either access the "manage staff" and "manage enrollment" buttons directly from the list of course, or access the course page, then click on the respective buttons.

Static image of path 1:

![screen shot 2015-06-17 at 6 32 47 pm](https://cloud.githubusercontent.com/assets/2068077/8222384/774866f0-151f-11e5-93ef-71df339600b0.png)

Path 2: 
![site-enrollment-manage](https://cloud.githubusercontent.com/assets/2068077/8222382/6cd0807c-151f-11e5-868c-052d5c4d3886.gif)

**Comment by alvinwan** [comment]
Possible to enroll a CSV of student emails.

@soumyabasu Could you take a look and let me know if it's good to merge?

![site-enrollment-manages](https://cloud.githubusercontent.com/assets/2068077/8222593/5120efc6-1522-11e5-97a2-4fd2056d6605.gif)

**Comment by soumyabasu** [comment]
That looks great- no other problems with this. Once your PR is merged ( @Sumukh should probably code review the frontend changes) feel free to close this issue.
