### ISSUE TITLE
Deal with missing indices in the Datastore

### ISSUE THREAD

**Issue by moowiz** [Cal-CS-61A-Staff/ok#247]
When we upload new datastore indices, they aren't available for a bit, until they've been built by the app engine service. We should show the user some sort of useful message about this, rather than just giving up and throwing a 500.

**Comment by papajohn** [comment]
I think no one can solve this issue but you, @moowiz , since I'm not sure how to replicate it. Want to either fix it or close it? Either is fine with me.
