### ISSUE TITLE
Queues should also provide basic information about the submission

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#283]
The detail page of queues provides just IDs of submissions. In order to display the needed information on the front-end - we need more information about each submission. 

The constraint here is that it can get slow to list all of the queues and get all of the associated submissions. We can solve this by only making this query for the queue detail page and every other query can just work with a list of ids.

**Comment by alvinwan** [comment]
@Sumukh Is this still the case? It seems like there's only one API call `pull`.
