### ISSUE TITLE
Make grading queues better.

### ISSUE THREAD

**Issue by moowiz** [Cal-CS-61A-Staff/ok#298]
It'd be great if we could add or delete submissions from grading queues when you're looking at it; maybe we could have delete buttons next to each one, and then have a search box by email for submissions? I'm having to manually delete submissions from the queues, which is pretty annoying. 

I'll need to add a backend endpoint for deleting submissions; let me know what you want that to look like.

**Comment by papajohn** [comment]
Queues seem pretty functional as-is. Can we close this issue?

**Comment by Sumukh** [comment]
Yeah.
