### ISSUE TITLE
Web-based search for submissions and students by email, submission time, etc.

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#305]
Putting an issue here to remind me. This may become more necessary for regrade requests and pulling submissions for specific students. There's currently no way to do this with the frontend.

**Comment by papajohn** [comment]
From @albert12132 :

- Be able to perform searches for student submissions, preferably with the ability to filter on user, timestamp ("submissions after ... time"), submissions that are flagged with --submit, and assignment
- Last I checked, this feature doesn't exist. This would be a game-changer for us.
