### ISSUE TITLE
Too many branches

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/ok#327]
This project has tons of branches, but I have no idea which ones are worth keeping/merging. Please reply with the names of any branches that are being actively developed. Then, someone (@some3141?) can clean out the rest.

**Comment by Some3141** [comment]
Here are a list of branches along with the last person to commit to them. Let me know if it contains anything useful:

analytics- @moowiz 
api- @moowiz 
autograder- @moowiz 
cleanup- @moowiz 
dashlist- @Sumukh 
final_submission_api- @moowiz 
frontend_create- @moowiz 
frontend_sort- @Sumukh 
hanging_fix- @sharadmv 
messages_to_json- @moowiz 
pagination- @sharadmv 
redesign- @sharadmv 
scripts- @Sumukh 
suppresslang- @Sumukh 
timestamp- @Sumukh 

I think most of these are one-off server features that never got created and probably are either in the pipeline or decided it wasn't a problem.

scripts should be moved to the ok-scripts-fa14 repo and (hopefully) never looked at or touched again.

**Comment by Sumukh** [comment]
All the ones listed for me are safe to delete.

**Comment by papajohn** [comment]
I suspect that almost all branches are stale now that we've made a substantial rewrite to the server, client, & front end.

**Comment by moowiz** [comment]
Deleted all my branches. They were stale, small one-off branches I never developed.

**Comment by Some3141** [comment]
Done. Deleted all of the branches that are stale.
