### ISSUE TITLE
Move templates from source to datastore

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/ok#328]
Right now it looks like assignment templates are here

https://github.com/Cal-CS-61A-Staff/ok/tree/master/server/app/seed

But we want them to be in the datastore. I think that means creating some (command line?) interface for uploading and viewing them.

**Comment by Sumukh** [comment]
These are seed files for local testing. They are inserting into the datastore when run locally. It's easier to work with actual project files on the database. I can change these to be smaller/non-project files if you'd like. 

The actual assignment templates we use for diffs are stored in the datastore with the assignment - it's a field when creating an assignment.  (https://github.com/Cal-CS-61A-Staff/ok/blob/master/server/app/models.py#L294)

**Comment by papajohn** [comment]
I see — that makes sense. No need to make changes, but adding this
description to a readme somewhere would be helpful. Thanks.

**Comment by Sumukh** [comment]
Marking as closed. I'll add a readme to the seed file folder.
