### ISSUE TITLE
Final Submissions do not merge when group invite accepted

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#331]
Case: I have a final submit. If Soumya invites me and I accept it we both now have no Final Submission. Backups and normal submissions work. 

@papajohn is this a design choice? From what I can read in the wiki - it doesn't appear to be. Relevant section quoted below: 

If it's not a design choice: @Some3141 

>Whenever a new active member is added to a group, the *group final submission is updated to the most recent submission* of any active member of the group.
Whenever the final submission of a person changes, that person should be notified with a link to the new final submission. This can occur because (a) they joined a group with a more recent final submission than theirs, or (b) someone else joined their group with a more recent final submission than the group's current final submission.

**Comment by papajohn** [comment]
That's a bug.

**Comment by papajohn** [comment]
I'm investigating now. Any news, @moowiz ? Thanks.

**Comment by papajohn** [comment]
Sorry, didn't make much progress, but at least I know what needs to be done. I can finish up after lecture. Started a PR: https://github.com/Cal-CS-61A-Staff/ok/pull/337

**Comment by moowiz** [comment]
Lemme make a test and add it to the PR for you.

**Comment by moowiz** [comment]
How were you checking that they had a final submission?

**Comment by Sumukh** [comment]
The frontend relies on `get_course_info` to render the dashboard (https://github.com/Cal-CS-61A-Staff/ok/blob/master/server/app/models.py#L212)

**Comment by moowiz** [comment]
Added a test for the bug.
