### ISSUE TITLE
logging in with Calnet ID for OK

### ISSUE THREAD

**Issue by jessiecgu** [Cal-CS-61A-Staff/ok#334]
for hw1, when I did python3 ok, they just asked me for my calnet id. The website says to use your berkeley email. I ended up typing in a random nonsense calnet id (not sure if this calnet id exists), but OK says that I was authenticated successfully.

I guess this might be a concern if a student accidentally types in a wrong calnet id without realizing it. Not sure if you can do anything about this though since you can't have access to their calnet id password. How can you verify that students send it to the right calnet id.

![screen shot 2015-01-25 at 4 48 53 pm](https://cloud.githubusercontent.com/assets/6174407/5894152/9be640aa-a4b2-11e4-8663-a05361c12a30.png)
![screen shot 2015-01-25 at 4 52 30 pm](https://cloud.githubusercontent.com/assets/6174407/5894153/9f871d92-a4b2-11e4-971d-61a7bc911edc.png)

**Comment by jessiecgu** [comment]
So I submitted with ok under a false Calnet ID, it was successful and they ended up giving me a link to the website too.

**Comment by Sumukh** [comment]
Did you login to Calnet or were you already logged in? If so, it's using whatever account you were logged in as. The username that you type in is just used to go the login screen.

**Comment by jessiecgu** [comment]
I don't think I was logged in. I guess it didn't matter cause at the website link, I had to enter in my actual Calnet ID with a password.

**Comment by Some3141** [comment]
Did you see that submission on the actual website?

Here's what might have happened (which I think is fine): When you enter your CalnetID, we go to Google and have them sign you in and we suggest an account. I'm guessing you were already logged into Google, which is why you might have authenticated automatically as your actual Calnet.

If that sounds plausible, feel free to close this issue.

**Comment by jessiecgu** [comment]
Ah no. I guess it's fine then ^^ Sorry about that then.

**Comment by Some3141** [comment]
Yeah, no problem- we hadn't really thought about this case, so it's great that you tested it out!
