### ISSUE TITLE
Integration test for final submissions is incomplete

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/ok#343]
I'm hoping we can have an API test that submits one time, creates a group, disbands the group, and creates another group. Throughout, we can verify that the API shows the correct final submission at all times.

I started to create such a test called `test_one_final`, but got stuck:
https://github.com/Cal-CS-61A-Staff/ok/blob/master/server/tests/integration/test_final_submissions.py#L76

Problems I had:
- My `get` request was mad because it said that they required `assignment` parameter didn't exist (but I tried to add it as data... maybe that's not the right way to create a `get` request.)
- My invite `post_json` request kept executing with `admin` as the user instead of `student0`, and the resulting group would fail to be created. I'm not sure how the user for a request is set in the testing framework.

**Comment by papajohn** [comment]
@moowiz I'm happy to try again myself if you can point me in the right direction.

**Comment by moowiz** [comment]
Sorry, let me look at this real quick and try to give you some tips.
