### ISSUE TITLE
Unique items clean-up

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/ok#344]
Should we have a deferred action to verify that each student has at most one group per assignment, one final submission, and one user per email address? If so, how?

**Comment by Some3141** [comment]
https://github.com/Cal-CS-61A-Staff/ok/blob/0dcbd1d3b8ddc4a2b9a1e0ec79a2329f7845d3b7/server/app/api.py#L658

You just define a function and give it the arguments. It looks like most of the deferred functions are in utils.py.

**Comment by moowiz** [comment]
What should happen if it turns out that they have more than one of these things?

**Comment by Some3141** [comment]
1 user per email address- we need to merge the User records.

1 final submission- we delete one and take the most recent one.

1 group per assignment- I really doubt this will happen, but maybe kick them out of all groups?

For merging users, I have a scheme that I think works. It's a complicated thing though.- @moowiz- can we talk about it offline?

**Comment by moowiz** [comment]
Sure, we can talk about it tomorrow?
