### ISSUE TITLE
Active assignments list includes assignments from other courses

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/ok#357]
E.g., `extra hw1` from CS 98 now appears on my 61A active assignments list.

**Comment by Some3141** [comment]
It's fixed now. The assignment POST request should check if the course exists before actually making it.

**Comment by papajohn** [comment]
I think we're talking about different bugs. I was pointing out a small UI bug that lists active assignments on the left pane of the assignment page for a course. It has extra stuff in it.

![screen shot 2015-02-01 at 1 49 24 pm](https://cloud.githubusercontent.com/assets/320145/5994005/4879f102-aa19-11e4-84e8-e051f3a3add3.png)

**Comment by Some3141** [comment]
Oh yes, we are talking about different bugs. I'll file a separate issue. XD
