### ISSUE TITLE
Firefox UI-Routing bug

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#366]
There's a bug with routing where on certain browsers the front-end doesn't route the URL correctly. The error is stored in [sentry](https://app.getsentry.com/cs-61a-uc-berkeley/ok-web/group/52212577/)

**Comment by alvinwan** [comment]
Is there a specific URL? Just tried it on FF and doesn't seem like anything is wrong. Maybe a better Angular... or we did something right. x)

**Comment by Sumukh** [comment]
Yeah - maybe. I haven't seen the error as much recently? The lab machines in berkeley occasionally had the error.
