### ISSUE TITLE
Make left list of assignments clickable.

### ISSUE THREAD

**Issue by moowiz** [Cal-CS-61A-Staff/ok#375]
The list of assignments on the left
![screen shot 2015-02-12 at 10 52 12 am](https://cloud.githubusercontent.com/assets/1504248/6174688/3c72479e-b2a5-11e4-9c46-0f3e13e0e32f.png)

should be clickable! 
I think that'd be awesome :)

**Comment by Sumukh** [comment]
Ok - I'm thinking that clicking on that - would filter the list of submissions displayed on the dashboard.
