### ISSUE TITLE
Frontend diffs can be difficult to read

### ISSUE THREAD

**Issue by albert12132** [Cal-CS-61A-Staff/ok#376]
Currently, a lot of diffs are displayed line-by-line:

![screen shot 2015-02-12 at 3 52 43 pm](https://cloud.githubusercontent.com/assets/2187524/6179585/7b06ae80-b2cf-11e4-820b-20c193d2c9dd.png)

It would be better to have a contiguous block of deletions (red) followed by a contiguous block of insertions (green).

**Comment by Sumukh** [comment]
It looks this happened because the indentation was changed. I think this actually should be backend change with how the diff objects are generated - https://docs.python.org/2/library/difflib.html

**Comment by alvinwan** [comment]
@albert12132 Does this still need amending?

**Comment by albert12132** [comment]
I haven't seen any recent reports of this issue.
