### ISSUE TITLE
Have User arguments make more sense

### ISSUE THREAD

**Issue by soumyabasu** [Cal-CS-61A-Staff/ok#378]
It's unclear from looking at api.py whether you should pass in an email or a user ID or what.

**Comment by alvinwan** [comment]
For posterity: `user` is the "current_user" - automatically taken care of by `APIResource` in line 222 of api.py.

```
...
http_method = request.method.upper()
        user = session['user']

        if path is None:  # Index
            if http_method not in ('GET', 'POST'):
...
```
