### ISSUE TITLE
Sidebar shows assignments from all courses

### ISSUE THREAD

**Issue by soumyabasu** [Cal-CS-61A-Staff/ok#380]
The sidebar that lists the assignments lists them for all courses, not just the current course. I think the API call needs to ask for slightly different fields.

**Comment by Sumukh** [comment]
What API endpoint/parameters should it be hitting?

**Comment by Some3141** [comment]
As far as I can tell, you're hitting the assignment API and making this call: 

https://ok-server.appspot.com/api/v1/assignment?fields=%7B%22id%22:true,%22display_name%22:true,%22due_date%22:true,%22points%22:true,%22created%22:true%7D&format=json

I think what you want is this (the course API):

https://ok-server.appspot.com/api/v1/course/5165212546105344/assignments
