### ISSUE TITLE
Frontend cleanup

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#381]
- [x] Student Facing Code View should be more like Admin code view. (Blocking: Student facing CSS is structured differently - @alvinwan 
- [x] Remove student facing code/comment fetching system - use something more like the admin view (the js for this would be much better if we used more angular) (depends on 1) 
- [x] Remove unnecessary front-end libraries 
- [x] Use a CSS framework for student frontend. @alvinwan 

Feel free to add more issues as you see them - this issue is focused on actual code cleanup.

**Comment by knrafto** [comment]
I think the interface should take a few ideas from Gradescope. IMO it's much cleaner and easier to use than the interface.
