### ISSUE TITLE
Assignments should contain links to their course page

### ISSUE THREAD

**Issue by soumyabasu** [Cal-CS-61A-Staff/ok#386]
The assignment links do not contain specific links to the project on the course website.

**Comment by Sumukh** [comment]
This is mainly a server change - the code is ready on the frontend.

**Comment by moowiz** [comment]
Do I need to work on this? 

Is this something that would show up on the frontend? What would you want the server to respond with?

**Comment by Sumukh** [comment]
Just needs a model change to store that information. Should be an easy change to the assignment model + api (to accept a link). Feel free to make the change - if not I'll get around to it soon.

**Comment by moowiz** [comment]
I'm not sure what this would look like... Could you give me an example?

It might be better if you just did this at some point.

**Comment by Some3141** [comment]
Basically, the Assignment model would have an attribute that says "link" (that contains the link to the project spec). I think that's it, since the GET should return that attribute anyway?
