### ISSUE TITLE
Support projects in iPython notebooks

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/ok#387]
Not for 61A, but I think there's value in targeting iPython notebooks. Here's a proposal:

- students download a zipped directory containing ok, some starter files, and a `.ipynb` file with a project description and a bunch of `%load` cells to load in the starter files.

- students edit the code in the iPython notebook 

- students can run `ok` from within the notebook using `%python ok` (I think)

- we have `ok` scrape the edited versions of the original files from the `.ipynb` file and submit them as if they were one flat file.

That way, courses could use `ok` without requiring knowledge of the command line or file system.

Thoughts?

**Comment by Some3141** [comment]
Do courses actually use iPython notebook? And if so, how widely is it used? I can see it being useful as a lecturing tool (since I saw it being used very effectively there), but am not 100% sure whether it's a good thing to include in ok if not many programming projects are done in this format. Also, from what you describe, I think it's an ok-client change not a server side change.

Personally, I like the idea conceptually and the proposal that you sketched looks solid to me. Just not sure about how much value this has.

**Comment by sharadmv** [comment]
I remember an EE upper division course (digital signals processing?) using IPython notebooks for labs and lab submission.

**Comment by papajohn** [comment]
EE 16A does everything in iPython. I do think we should aim for a
client-only change that is as small a change as possible, but integrates
well with the format.

**Comment by sharadmv** [comment]
`ok` could just run `ipython nbconvert` to convert the notebook into an ordinary python file. Or perhaps import IPython functionality itself.

**Comment by papajohn** [comment]
My best guess right now is that multiple files will be in the same
notebook, so we might need to do something a little more clever, but I
think traversing a notebook is really easy — it's just JSON.

**Comment by Some3141** [comment]
Does EE 16A have a sample assignment that we can play with? (Second reason I asked about who was using it :P)

**Comment by papajohn** [comment]
http://inst.eecs.berkeley.edu/~ee16a/sp15/Homework/HW0/
http://inst.eecs.berkeley.edu/~ee16a/sp15/Homework/HW1/
http://inst.eecs.berkeley.edu/~ee16a/sp15/Homework/HW2/

**Comment by papajohn** [comment]
Thanks for the feedback. I'm going to try to put together a prototype for an ipython-based project in the next week or two (in a separate repo). I'll post links here in case anyone wants to follow along & help.

**Comment by Some3141** [comment]
That sounds great, but is there a reason that we can't just use the EE 16A projects to test out our prototypes? Either way, I think that we will need a demo project in https://github.com/Cal-CS-61A-Staff/ok-client/tree/master/demo to write tests against.

**Comment by papajohn** [comment]
On Sun, Feb 22, 2015 at 12:42 PM, Some3141 <notifications@github.com> wrote:

> That sounds great, but is there a reason that we can't just use the EE 16A
> projects to test out our prototypes?
>
That's fine too — I just want to learn iPython and try out some different
project structures (mostly whether to use/distribute separate files or not).

**Comment by Some3141** [comment]
Ah, okay. I just wanted to be sure that the sole reason wasn't to give us another assignment to play with. XD

**Comment by alvinwan** [comment]
@papajohn Do we still want this? Considering DS10 especially. I don't traversing a JSON should be that hard, and I can just continue modding the notebook.

**Comment by papajohn** [comment]
I think we still want this, but I need to build some assignments for that
class before we can really make much progress.

**Comment by alvinwan** [comment]
Ok-client adaptation: https://github.com/Cal-CS-61A-Staff/ok-client/pull/112
UI: https://github.com/alvinwan/notebook/pull/1
