### ISSUE TITLE
UI nit: Font is thin on some computers/browsers

### ISSUE THREAD

**Issue by sharadmv** [Cal-CS-61A-Staff/ok#390]
Just a minor UI nit. It seems a bit hard to read the "Better programming projects", given that it's a thin white font partially on a white background.

Similarly, "RUN TESTS, TRACK PROGRESS, AND ASSIST IN DEBUGGING" is partially on top of the silver Mac keyboard.

![splash](https://cloud.githubusercontent.com/assets/1142926/6320711/6c6841ea-ba9a-11e4-8cad-8a751a65511d.png)

**Comment by Some3141** [comment]
I think this is the old landing page- though I'm not sure if it's still an issue on the new landing page. (ok-server.appspot.com/landing).

**Comment by sharadmv** [comment]
Yea I got this from okpy.org.

It's definitely better on the new landing page, but I think the same thing applies to the "run tests" text.

![splash2](https://cloud.githubusercontent.com/assets/1142926/6320774/e1a7581e-ba9b-11e4-8987-e904e2882fc7.png)

**Comment by Some3141** [comment]
I think this might look a little better: (The location of the text changes based on the screen size). I think it should be in a fixed place and in a nice place to read.

![screen shot 2015-02-22 at 2 14 16 pm](https://cloud.githubusercontent.com/assets/1359998/6320804/1e36bf8a-ba9d-11e4-9ca9-62d75ba4ebff.png)

**Comment by Some3141** [comment]
Also see #392.

**Comment by sharadmv** [comment]
Seems like this may be a different issue. Right now, the website for me is using Raleway 100 (http://www.google.com/fonts/specimen/Raleway). Is that the same for everyone else?

**Comment by Some3141** [comment]
MIne is: fonts.gstatic.com/s/opensans/v10

**Comment by alvinwan** [comment]
@sharadmv @Some3141 I upped the font weight to 200 but kept the Raleway font. I've checked this on safari and ran it on sauce. Doesn't seem to be choppy anymore, but correct me if I'm wrong:

![screen shot 2015-03-04 at 1 31 01 pm](https://cloud.githubusercontent.com/assets/2068077/6493911/e6ccd290-c272-11e4-80f5-154480cad1f5.png)
