### ISSUE TITLE
UI nit: splash login button a bit small (or redundant?)

### ISSUE THREAD

**Issue by sharadmv** [Cal-CS-61A-Staff/ok#391]
Not sure if it's just for my computer, but I think the top-right login button seems either redundant, and too small if it's not. Is there any reason why we have two login buttons?

![login](https://cloud.githubusercontent.com/assets/1142926/6320731/e3086ce4-ba9a-11e4-9f83-221cbb871b06.png)

**Comment by Some3141** [comment]
The middle button becomes a "Go to the Student Dashboard" button while the top right button is for logging in and logging out.

**Comment by Sumukh** [comment]
This is there to support the default interaction of having a login button on the top-right. As @Some3141 mentioned - this becomes a logout button.
