### ISSUE TITLE
UI nit: course box hard to read

### ISSUE THREAD

**Issue by sharadmv** [Cal-CS-61A-Staff/ok#392]
It may be just my opinion, but I think the thin white font on this dynamic background with light elements in makes the course name a bit hard to read.
Similarly, the UC Berkeley font is extremely small and could be featured a bit more prominently.
The "COURSE HAS BEGUN" text, although sitting on a darker background, is also extremely thin and strains the eyes a bit.

![course](https://cloud.githubusercontent.com/assets/1142926/6320749/2fa56548-ba9b-11e4-9eb2-43aa0a831af9.png)

**Comment by Some3141** [comment]
Closed via #390
