### ISSUE TITLE
okpy.org and ok-server.appspot.com have different landing pages

### ISSUE THREAD

**Issue by soumyabasu** [Cal-CS-61A-Staff/ok#393]
I think ok-server.appspot.com is the correct landing page.

**Comment by alvinwan** [comment]
@Sumukh Did you get a chance to look at this? Don't think this is something I have control over. x)

**Comment by Sumukh** [comment]
I haven't. I'll try to keep them in sync. Remind me if I don't update it.

**Comment by alvinwan** [comment]
Sounds good!

**Comment by Sumukh** [comment]
okpy.org now redirects to ok-server (over https)

**Comment by alvinwan** [comment]
*like 👍🏻
