### ISSUE TITLE
Add info about front-end on the Wiki

### ISSUE THREAD

**Issue by kyletliang** [Cal-CS-61A-Staff/ok#396]
Can we get more information about how the front-end code is laid out and organized on the wiki so that it will be easier for new people to understand what needs to be worked on? Currently, my group is working on adding accessibility features and it's a little unclear as to how much we need to modify. (Pinging Sumukh?)

**Comment by negativetwelve** [comment]
You can @ mention people and they'll get email notifications!

cc @Sumukh

**Comment by Sumukh** [comment]
Sure. I think it'd be helpful to meet and we can go over how the front-end is laid out. Send me an email with when your group is available to meet. 

A high level approach is that the templates are the foundation of the page (The student one is server/app/templates/student.html). This defines the basic layout and necessary support files (CSS, JS etc). 

Inside the template - we include the Angular app (server/static/js/student.js) that tell us what pieces are needed for that page. It then loads "partials" [(example)](https://github.com/Cal-CS-61A-Staff/ok/tree/master/server/static/partials/student) (which are parts of the page, like the assignment count or the list of assignments). 

Each of these partials have some part of the page [(example)](https://github.com/Cal-CS-61A-Staff/ok/blob/master/server/static/partials/student/assignment.module.html). You'll notice these partials have things that looks like variables `{{course.website}}` - this data is filled in by Angular and the data is filled in by the controller (visible at the top of the partial). (The controllers for the student front-end are [here](https://github.com/Cal-CS-61A-Staff/ok/blob/master/server/static/js/student/controllers.js)

ng-aria will be a helpful library here - it plugs into Angular 
[documentation](https://docs.angularjs.org/api/ngAria)
[talk about it on youtube](https://www.youtube.com/watch?v=dmYDggEgU-s)

If you want more info about Angular - [getting start guide](https://docs.angularjs.org/misc/started)

**Comment by Some3141** [comment]
*cough* put it on the wiki *cough*

**Comment by Sumukh** [comment]
https://github.com/Cal-CS-61A-Staff/ok/wiki/Frontend 

Send me an email if you have questions.
