### ISSUE TITLE
Bug in diffs.

### ISSUE THREAD

**Issue by moowiz** [Cal-CS-61A-Staff/ok#398]
There's a bug in diffs.
![screen shot 2015-02-25 at 5](https://cloud.githubusercontent.com/assets/1504248/6384809/94630986-bd16-11e4-859c-428d1323f016.png)

**Comment by Sumukh** [comment]
Initial guess is that because there are no templates for this assignment?

**Comment by Sumukh** [comment]
Should be resolved via #399
