### ISSUE TITLE
Define protocol for talking to autograder

### ISSUE THREAD

**Issue by moowiz** [Cal-CS-61A-Staff/ok#4]
We need to decide how we want to talk to the autograder.

Do we want to use the edX autograder protocol? It looks like they send the password in plaintext...?

If we make our own, we should document this in the wiki.

**Comment by Some3141** [comment]
I think @kvchen and @Sumukh are working on an autograder now.

**Comment by papajohn** [comment]
I believe this was finished by @joseph-choi and co.
