### ISSUE TITLE
CSS based line numbers don't match actual line numbers

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#400]
There's 1 - 5 line margin of error on the line numbers on the student facing code review site. This is important for students looking at code review because the comment can be line sensitive. 

This links to issue #381 - I think it's worth moving off a css dependent approach to line numbers and adopt the codereview/diff view of the admin. All we have to do is tweak some CSS - but this will become much easier when we transition over to using a CSS framework for the frontend.

**Comment by Sumukh** [comment]
@alvinwan - Any updates on this? This will be important to have fixed before the next set of code-review is published

**Comment by alvinwan** [comment]
taking a look at it now
