### ISSUE TITLE
Performance Goals

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#401]
I'd really like to see some performance improvements. Let's set some goals for performance. 

What do you think would be things to measure performance. 

I suggest using some of these metrics

- Frontend Page Load (Time)
- *Student Assignment Dashboard* (Time)
- Client -> Server Submission (Time)
- Client -> Server Backup (Time) - Ideally have the server respond before the timeout. We can't solve all cases of this - but we should try to. 
- *Staff -> Dashboard Load Times.* (Time) - Takes over 15 seconds now
- Staff -> Check for individual Queue (Time)  - Not even on front-end currently  
- Staff -> Load All Queues (Time) - Takes over 15 seconds
- Staff -> Load A Queue (Time) - this is pretty fast already

Things currently being done to improve performance

- Upgraded instance size.  
- More caching on the student frontend, so loading indicators show up less frequently. 
- Caching on the staff side 
- Utilizing memcache more for queries.
- Aggressive time out on the client (though this results in more user facing errors) 
- Memcache was sitting at its 1GB limit - I've bumped the size - so we'll also see if that helps with performance.

**Comment by Some3141** [comment]
Can we combine this into "Average page load time"? Eventually, we want a weighted average so that pages that are accessed more frequently get more weight in the average, but... I think the former is better.

**Comment by moowiz** [comment]
Totally agree. This would be great to keep track of.

I think there's a new feature called "Traces" in app engine that helps you
out with this. @denero can you enable that somehow?

also, we should look at percentile load times. I remember that was standard
practice for my internships when they looked at performance. See what the
90th percentile load time is rather than just the average.

**Comment by papajohn** [comment]
I did not find a way to enable `Traces` in AppEngine. Do you have instructions somewhere?

**Comment by Sumukh** [comment]
`Traces` is already enabled - it's under Monitoring on the developer console.

**Comment by knrafto** [comment]
v2 is no longer being maintained.
