### ISSUE TITLE
Integrity issue caused 500

### ISSUE THREAD

**Issue by moowiz** [Cal-CS-61A-Staff/ok#403]
There was a `group` key in a `FinalSubmission` which was invalid. Not sure exactly why this happened, but it caused an error when indexing over all the queues. Dumping relevant info here...

The key of the user who's group didn't exist was `Key('Userv2', 6459788837781504)`
The deleted group was `Key('Groupv2', 4661627957805056)`
The new group was `Key('Groupv2', 5287953559453696)`
The final submission was `Key('FinalSubmissionv2', 6135067222999040)`

**Comment by alvinwan** [comment]
Only place where FinalSubmission is created in `models.py` at 369:

```
           if latest:
                FinalSubmission(assignment=assignment,
                                group=group.key if group else None,
                                submission=latest.key).put()
```

Per the Group model at line 1018, "Empty/singleton groups are deleted." This was probably the issue:

```
        error = self.validate()
        if error:
            self.key.delete()
        else:
            self.put()
```

Going to try and fix this.
