### ISSUE TITLE
How should people add analytics jobs?

### ISSUE THREAD

**Issue by soumyabasu** [Cal-CS-61A-Staff/ok#409]
There's the current way, which is that they fork the repo, add their stuff and make a PR. A second way is to submodule their repositories and make a directory, so that they can just add jobs.

I'm biased towards the former because it seems like the latter would be a security vulnerability since people can add arbitrary code to our repo and we'd have to monitor many repositories to figure out what's going on with our server. However, I also haven't used submodules extensively so I might just not know all of the features.

@papajohn @sharadmv @moowiz @Sumukh - what do you think?

**Comment by moowiz** [comment]
As some background; I thought of submodules, and thought that might be a nice use case for them in this project. @Some3141 might be right though...

**Comment by sharadmv** [comment]
For now, I think that we should define a set of "core" analytics that a staff might be interested in and write them ourselves. We can expose them via some sort of staff analytics dashboard. If a staff member wants a new analytic, they can send us a PR. We can start thinking about the types of jobs that people want and how we can best fit those needs.

However, I don't think forking/PR and submodules are a scalable or long term solution to allowing staff to flexibly run customizable jobs.

**Comment by papajohn** [comment]
I agree that fixing the suite of analytics and always running them is the
right way to start. Probably the best way to run truly custom jobs is to
provide a full data export.

**Comment by Sumukh** [comment]
Closing because v3 uses a web based UI tool to run analytical queries:  
![image](https://cloud.githubusercontent.com/assets/882381/17575241/922b477e-5f1c-11e6-8773-0f4c9bc82281.png)

**Comment by sharadmv** [comment]
:(
