### ISSUE TITLE
Get course info for a user takes a long time

### ISSUE THREAD

**Issue by moowiz** [Cal-CS-61A-Staff/ok#412]
This is the amount of time it takes to get a users course info. We should try to make this much faster. We should batch process a lot of this.

There are about 400 RPCs in this. That's a lot of individual RPCs.

![screen shot 2015-03-09 at 5 13 44 pm](https://cloud.githubusercontent.com/assets/1504248/6567125/abf797d4-c67f-11e4-829c-f0c5f502b9d8.png)

![screen shot 2015-03-09 at 5 14 29 pm](https://cloud.githubusercontent.com/assets/1504248/6567136/c9faa99c-c67f-11e4-94b8-41920379dc6e.png)

**Comment by Sumukh** [comment]
Yeah - it'd be great to make this faster. Feel free to try to optimize this - or we can just breakup the way the front-end makes calls. 

The current plan was the have the frontend make two queries - for active submissions and inactive submissions.

**Comment by Sumukh** [comment]
Fixed thanks to @knrafto in #583
