### ISSUE TITLE
Version Creation mark as current is broken

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#423]
The admin front-end uses the Version creation endpoint - and there's a mark as current version checkbox - however currently it doesn't seem to actually change the actual version. 

This could be a server or frontend issue - but it needs more investigation.

**Comment by albert12132** [comment]
Has this been fixed? I happen to need to update ok-client's version to v1.3.31.

**Comment by Sumukh** [comment]
It has not. @moowiz - I think you originally wrote this right? 
@albert12132 - I can add you to the app console and you can edit it there.

**Comment by papajohn** [comment]
albert...@gmail.com now has edit permissions for ok-server

-John
