### ISSUE TITLE
Show diff of backup

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/ok#425]
A student suggested that it would be nice to see a diff view of his backups, just to understand what had changed in the program so far.

**Comment by Sumukh** [comment]
Is this a diff to the template? Right now we'd only support this for projects because those are the only assignments with templates

**Comment by papajohn** [comment]
I think the idea is to get a diff to the template for any back-up, so that
he could see what he had changed and notice if he had accidentally changed
something he didnt' mean to change (or track partner progress).

**Comment by knrafto** [comment]
Fixed in v3. v2 is no longer being maintained. Possibly related to #671
