### ISSUE TITLE
get_submissions api shows all backups, not just submissions

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/ok#427]
As a result, when students view their submissions, they see all backups.

**Comment by Some3141** [comment]
Also, things without file_contents are showing up as well- I think that might be a result of the optimization that was made yesterday.

**Comment by Some3141** [comment]
This has been fixed with the last few commits ending here: 673faa307cc860efa80a047ea6f8d6d59dbea6fd. Nice job Stephen!
