### ISSUE TITLE
Autograding 

### ISSUE THREAD

**Issue by joseph-choi** [Cal-CS-61A-Staff/ok#431]
Hi staff, the cs169 team has been researching sandboxing possibilities and the solution we currently have is PyPy3.2.4. Here's the overview: http://pypy.readthedocs.org/en/latest/sandbox.html 

Would this be what we are going for? 
If not, could you guys provide other possible solutions? We heard that EDX had a solution and that you guys looked into it. Could you guys send that to us if possible also. 

Thanks

**Comment by Sumukh** [comment]
I'd suggest taking a look into using Docker. I'd be happy to talk more about this in person along with @Some3141 .

**Comment by papajohn** [comment]
I think we're close to having an autograder running for OK submissions, based on the presentation two weeks ago, but it would be great to have this feature up and running before summer session starts in mid June.

**Comment by albert12132** [comment]
Is there any progress on creating a web interface for autograding? In particular, I'd like to have the following:

* A "Grade all" button that grades all final submissions for a given assignment and assigns scores.
* A "Grade submission" button that grades a particular submission. There's also the question of when a grade will be considered "final". Under the glookup framework, grading a particular submission doesn't immediately make that new score final; it is up to the instructor to determine whether or not to make it the final score. For that reason, I'd also like to have a "make final score" button that appears after "grade submission" completes. This would also be a natural way to facilitate regrades (simply grade another submission).
* An "Export grades" button for exporting all grades for a particular assignment (or even for all assignments in the class).

**Comment by joseph-choi** [comment]
Sorry Albert,
But I won't be working on it.

I'm not sure if Fred will be working on it though.
He's the one who presented on it (fredhong@berkeley.edu)

On Sat, Jun 6, 2015 at 11:13 AM, albert12132 <notifications@github.com>
wrote:

> Is there any progress on creating a web interface for autograding? In
> particular, I'd like to have the following:
>
>    - A "Grade all" button that grades all final submissions for a given
>    assignment and assigns scores.
>    - A "Grade submission" button that grades a particular submission.
>    There's also the question of when a grade will be considered "final". Under
>    the glookup framework, grading a particular submission doesn't immediately
>    make that new score final; it is up to the instructor to determine whether
>    or not to make it the final score. For that reason, I'd also like to have a
>    "make final score" button that appears after "grade submission" completes.
>    This would also be a natural way to facilitate regrades (simply grade
>    another submission).
>    - An "Export grades" button for exporting all grades for a particular
>    assignment (or even for all assignments in the class).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Cal-CS-61A-Staff/ok/issues/431#issuecomment-109627514>
> .
>



-- 
*Joe Choi*
*Declared Major: Computer Science*
University of California, Berkeley | 2015
joechoi@berkeley.edu | (858)-922-7950

**Comment by papajohn** [comment]
It looks like I'll have to pick this one up or it won't get done. I'll
report on my progress by Saturday.

**Comment by papajohn** [comment]
I didn't make progress yet... maybe tomorrow.
