### ISSUE TITLE
Handle Multiple Submissions (Checkpoints for Final Submissions) 

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#433]
For Scheme - We could handle this in a similar way to composition revisions - but just generalize it. 

Your final submission is always most recent submission (before the deadline) - and the checkpoints have a deadline in which in stores your most recent submission (if any) before the deadline. When we get a submission we'd look at the checkpoints and bucket the submission appropriately. If none of the checkpoints are active - then we reject the submissions. 

The only issue I see right now is having to create DB fields in which we store the checkpoint submission data in FS. It might not be possible to do as separate fields if we want to store arbitrary amounts of checkpoints. 

An alternative solution is to develop a search for all submissions - before some time via the API. This is going to be pretty slow. I prefer generalizing the first. 

I can work on this mid-week.

**Comment by Some3141** [comment]
I think that we either have to generalize revisions or just tweak it slightly to make this work.

@Sumukh - I assigned this issue to you, but please ask if you need help coding this up or whatever. You can also just point someone in the right direction if you don't have time.

**Comment by papajohn** [comment]
What about just adding an api call to get the last submission before a time
(and not changing the model)

**Comment by Sumukh** [comment]
Yeah - that is an option. I think multiple deadlines was only a issue before because we didn't have a table of submissions vs. backups & now we do. 

@Some3141 - would that be sufficient for grading?

**Comment by Some3141** [comment]
Yes, it would be. I like the API call idea. I think it should just be another parameter to the get_submission API call.

**Comment by alvinwan** [comment]
Supported by Search API if needed, but doesn't seem pertinent as FinalSubmissions might not be the latest submission now.
