### ISSUE TITLE
Web interface to create queues for composition grading

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/ok#441]
I thought this button existed at one point, but couldn't find it just now... I think a natural place for such a button would be the staff-facing assignment-edit page.

**Comment by alvinwan** [comment]
@moowiz Would you happen to know where the "make queue" button currently lives? Or, if it doesn't, does assign_queues have something to do with this?

**Comment by moowiz** [comment]
Sorry about getting back to you late; there currently isn't a way to make queues on the server right now. That has to be done through the `make_queues.py` file in the ok-scripts repository. Sorry things are a bit disorganized right now.

Currently, this would be moderately hard to do on the website, as opposed to through a script. The hardest part of that would be getting a list of the readers assigned to the particular course, which should be... decently easy? I'm not exactly sure. But, once you have that list, constructing the queues should prove to be easy.

**Comment by alvinwan** [comment]
@moowiz 

I see. I don't have access to the `ok-scripts` repository, though. Could you email me the contents of `make_queues.py` or otherwise give me access to the script? Still fumbling around, and would like to see how it was previously done. x)

**Comment by alvinwan** [comment]
I quote Soumya:

Premise: "Here's a list of composition grading staff and an assignment" (User specifies this on a pretty page)
- Then, the following is done:
    - For each staff, make a new queue for that assignment.
    - Each FinalSubmission has a queue attribute, and those are evenly distributed across the staff.

**Comment by Sumukh** [comment]
Clarifications: 
composition grading staff == course staff
Each FinalSubmission has a queue attribute, and those are evenly distributed across the (assigned/selectede) staff.

This could be done on the assignment page (or somewhere else - but the assignment detail page seems like a good place to start)

**Comment by soumyabasu** [comment]
> composition grading staff == course staff

Not necessarily. e.g. John doesn't grade, but needs instructor access.

**Comment by Sumukh** [comment]
^ Right - To make that more clean 
> Here's a list of composition grading staff

to "Here's a list of course staff"
