### ISSUE TITLE
Document the submission/comment/resubmission process for staff

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/ok#442]
There's some mechanism for accepting re-submissions based on staff composition comments, but I think it's not written down anywhere. Assuming all the functionality we need for composition grading is already in place, it would be great to write down how it's supposed to be administered.

**Comment by hwhuang** [comment]
Not quite sure where I should put my minimal documentation (that's open to edits!)

**Comment by soumyabasu** [comment]
Make a new wiki page and we'll add to it as necessary (and if questions come up)

**Comment by hwhuang** [comment]
How To Allow Students to Resubmit:

To allow students to resubmit, enable a flag on the actual assignment. Note: this will not turn on the composition feedback feature.

Enable the boolean in ok/server/app/models.py:

revision = ndb.BooleanProperty(default=False)
https://github.com/Cal-CS-61A-Staff/ok/blob/master/server/app/models.py#L488

The api that accepts resubmissions in ok/server/app/api.py:

def submit(self, user, assignment, messages, submit, submitter=None):
https://github.com/Cal-CS-61A-Staff/ok/blob/master/server/app/api.py#L1128
(A student must have a previously graded assignment to resubmit)

**Comment by alvinwan** [comment]
@hwhuang Enabling revisions is actually now available through the dashboard. Go to All Assignments > Edit, select True from the "Revisions" field, and hit save.

**Comment by hwhuang** [comment]
Noted, thanks @alvinwan 
I think @soumyabasu is making a wiki, unfortunately I don't have access

**Comment by alvinwan** [comment]
@hwhuang Ahh, gotcha. No worries. I just merged this new feature with master yesterday, so only a few people know about it. I'll write a document for all of our features soon, perhaps to add to Soumya's?

**Comment by alvinwan** [comment]
Documentation added: https://github.com/Cal-CS-61A-Staff/ok/wiki/Staff-:-How-to-Administer-Composition-Grades
