### ISSUE TITLE
Composition score export as CSV

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/ok#443]
The "Edit assignment" page should have a button to export composition scores as a CSV file.

**Comment by LuiseV** [comment]
I would like to works on this. I haven't had a chance to look closely at the code yet, but I might come up with some questions when I do.
-Luise

**Comment by LuiseV** [comment]
I'm trying to look at this now, and have a few questions. 
What information would you like in the csv? Student and both composition score and composition message? Or just student and score? 
And now that a student might be registered with several emails, should I just represent each student by the first one of these? 
Also, I am not really experienced with frontend. Should I try to figure out how to make a button that prompts a CSV download, or is a command line tool okay for starters? 
Thanks

**Comment by moowiz** [comment]
Hi Luise,

You should make an API endpoint on the backend which creates the csv file, and then create a button on the frontend which calls that API endpoint. That's the standard way we've been doing this; a javascript frontend, and a python backend, with the frontend calling the backend.

**Comment by soumyabasu** [comment]
In the csv, you should probably just have everything that the score model provides, so:

- the student
- the score
- the grader
- the submission

And whatever else you think might be useful. You should err on giving more information rather than less since the downloader can either specify what they want through your API or just parse out the columns that they need.

**Comment by LuiseV** [comment]
Great, thanks. I am not very experienced with this kind of bigger python projects - and have no experience with Javascript and HTML - but I will give it a shot and try my best! :)

**Comment by papajohn** [comment]
The most important issue here is to ensure that you generate valid CSV. I'd
suggest using https://docs.python.org/2/library/csv.html instead of
constructing the string representation of the result directly.

**Comment by alvinwan** [comment]
@LuiseV How's it coming along? Do you need help?

**Comment by LuiseV** [comment]
@alvinwan I think the backend is ready soon. If there is time, I will try to take a look at the frontend for a bit to see if I can figure it out. Most likely, I will need help with that part. Do you think you can help me with that at some point? :)

**Comment by alvinwan** [comment]
@LuiseV Awesome! Just let me know. I made edits to Soumya'a doc for the front-end; it gives a cursory overview of which files to update: https://github.com/Cal-CS-61A-Staff/ok/wiki/Developers--Getting-Started-with-OK

**Comment by alvinwan** [comment]
@LuiseV Could you create a new branch and push changes on?  Once I'm done with some other features, I'll come back to this... hopefully in the next couple hours. No worries if you're unable to; I'll start from scratch, and we can compare our approaches.

**Comment by LuiseV** [comment]
@alvinwan Sorry, I don't see this till now. The front end doc looks good - I just sent you and Soumya a few suggestions for it. 
I realized that your implementation of the zip download of submissions seem very similar to my implementation of the csv download. I'm at a point now where I would like to test it. Can you tell me how you tested your zip feature? How do you imitate the server calls for instance? Feel free to shoot me an email if you feel that is better :) 
Also, I'll make a branch now :)

**Comment by alvinwan** [comment]
@LuiseV Sounds good. The download link on the front-end is actually a direct API call; the backend just needs to return a file object's data with the proper headers. It'll be easier to zip everything up, as you can use the following functions from utils.py:
*You can find explanations for these functions in the code.

- start_zip : start a new zip
- add_to_zip : add file_contents (dictionary of filename -> string of contents) to specified zip
- finish_zip : return string of zip for output

Or, use the original method that Stephen created, called create_zip, which does all of the above in one step. All I did was split his method up into chunks, so that I could zip up a series of file_contents.

**Comment by LuiseV** [comment]
I think the csv download is ready now. I have tested that the back end code works and that the URL for the API call goes through. I followed @alvinwan's instructions on implementing the front end code, but I am not sure how to test whether it works. Can someone please explain how to test it, or tell me if there is something I need to fix? Should I make a new pull request?

**Comment by alvinwan** [comment]
@LuiseV Does clicking on the button actually download a CSV?

**Comment by LuiseV** [comment]
Thanks. After doing `bower install`, I can see a functioning website with the seed content (didn't have that before). It doesn't work completely yet, so I will fiddle around with it, and let you know when it works.

**Comment by alvinwan** [comment]
Awesome. Looks like we guessed the right (or at least an acceptable) version. Let me know if you need help.

**Comment by LuiseV** [comment]
The frontend looks good now, and clicking the button makes the correct API call. I can see that the API call completes, and the CSV is created, but the download doesn't actually happen. The download completes flawlessly, though, if I make the API call directly with localhost:8080/api/v1/assignment/6298002603900928/download_composition_scores where 6298002603900928 is the assignemnt ID. I haven't been able to find a solution yet. @alvinwan do you know why this might be?

**Comment by alvinwan** [comment]
Basically, AngularJS cannot accept FileTypes. The only way it would've worked is if the API returned a string, and JS generated a file for download. That's little troublesome though; I tried explaining this earlier, but I was probably unclear; you basically link the button *directly to the API call*. Skip the JS entirely. That's how I got the .zip download to work.

**Comment by LuiseV** [comment]
@alvinwan Sorry, I completely missed that. But now it works. Thanks for your help!

**Comment by LuiseV** [comment]
Everything should be working now

**Comment by alvinwan** [comment]
No worries. Awesome! Now we just have to wait for @Sumukh or @soumyabasu for code review, or maybe even Professor DeNero himself.
