### ISSUE TITLE
Program or web interface to download all submissions for an individual student

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/ok#445]
Requested by @albert12132 (though I don't think this functionality is currently used/needed regularly).

**Comment by moowiz** [comment]
Theoretically should be fairly easy to write a program to do this. Maybe ~2 hours of work. If you want it done at some point, just let me know and I could whip it up, I believe.

**Comment by soumyabasu** [comment]
I already have a script that does very similar things and @jathak is working on a PR in ok-client that ports that over (https://github.com/Cal-CS-61A-Staff/ok-client/pull/77)

Thanks a lot for offering though!
