### ISSUE TITLE
Assignments should be listed per-course for instructors

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/ok#447]
Right now, all assignments (ever) are listed together on the assignment page. Instead, I think they should always be filtered by course.

`https://ok-server.appspot.com/manage#/assignment/`

**Comment by moowiz** [comment]
This is a frontend change, correct? Or at least, this filtering could be done on the frontend, right?

**Comment by alvinwan** [comment]
Functionality added.
