### ISSUE TITLE
Create/edit assignment templates

### ISSUE THREAD

**Issue by alvinwan** [Cal-CS-61A-Staff/ok#451]
In the admin panel, creating/editing an assignment doesn't actually allow you to do anything with templates... yet. Putting it aside for now, as something that I couldn't figure out.

**Comment by Sumukh** [comment]
Bumping this. I just had to use the remote api to fix some templating issues. This is one of the last tasks we still use scripts for so it'd be great to get this done through the dashboard.

**Comment by knrafto** [comment]
v3 has an interface to upload templates. v2 is no longer being maintained.
