### ISSUE TITLE
Move Enrollment API out of urls.py

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#457]
The enrollment api shouldn't be in urls.py 

We can define the API endpoint there (see the bottom of urls.py) - but it should be in api.py

**Comment by alvinwan** [comment]
Mhm. Not sure if I'm missing something, but what needs to be removed? There isn't an `EnrollmentAPI` defined in the file or in the project.

```
register_api(api.AssignmentAPI, 'assignment_api', 'assignment')
register_api(api.SubmissionAPI, 'submission_api', 'submission')
register_api(api.SearchAPI, 'search_api', 'search')
register_api(api.VersionAPI, 'version_api', 'version')
register_api(api.CourseAPI, 'course_api', 'course')
register_api(api.GroupAPI, 'group_api', 'group')
register_api(api.UserAPI, 'user_api', 'user')
register_api(api.QueueAPI, 'queue_api', 'queue')
register_api(api.FinalSubmissionAPI, 'final_submission_api', 'final_submission')
register_api(api.AnalyticsAPI, 'analytics_api', 'analytics')
```

**Comment by soumyabasu** [comment]
Sumukh is saying that the "/enrollment" route shouldn't be there and should be part of some API in the section you quoted. Specifically, this function should be gone: https://github.com/Cal-CS-61A-Staff/ok/blob/master/server/app/urls.py#L64.

**Comment by alvinwan** [comment]
Ohh. Thanks. Working on it.
