### ISSUE TITLE
Download ZIP from search can't be decompressed. 

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#462]
(The download all submissions zip) 

I'd show you the file - but it can't be attached. :open_mouth: 

This isn't high priority.

**Comment by alvinwan** [comment]
I just tried it and it seems to work fine... does the single-file download work for you? Both methods use identical mechanisms.

![zip-download](https://cloud.githubusercontent.com/assets/2068077/8269555/c7791440-1762-11e5-8951-1bcd456f1106.gif)

**Comment by Sumukh** [comment]
Update: It seems to work - but the download all submissions doesn't download all of the submissions - just the ones on the page?

**Comment by alvinwan** [comment]
Mhm. That shouldn't happen - I'll investigate.

**Comment by albert12132** [comment]
I just tried doing a single-file download, and I wasn't able to unzip the resulting archive:

```
Archive:  <redacted>.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of <redacted>.zip or
        <redacted>.zip.zip, and cannot find <redacted>.zip.ZIP, period.
```

**Comment by alvinwan** [comment]
Mhm. Which browser were you using? Was `<redacted>.zip` the name of the resulting file?

**Comment by albert12132** [comment]
I'm using Chrome. Yup, `<redacted>.zip` is the name of the resulting file.

**Comment by alvinwan** [comment]
Mhm. I'll take a look.

**Comment by albert12132** [comment]
Any progress on this? Still can't decompress individual submissions (or any of the archives downloaded from the submission search page, for that matter).

**Comment by alvinwan** [comment]
Use safari for now.

**Comment by alvinwan** [comment]
Not really sure what to change - I'll update this thread if I find anything though.
