### ISSUE TITLE
Partner invitation errors

### ISSUE THREAD

**Issue by albert12132** [Cal-CS-61A-Staff/ok#467]
Students can't invite other students, even when both students have signed into okpy.org and neither are already in a group.

**Comment by alvinwan** [comment]
@albert12132 Make sure that both students are also enrolled in the course (login > all courses > manage enrollment). Try it again, and let me know.

I just tested it (partner1@teamwork.com inviting partner0@teamwork.com)

![partner-invite](https://cloud.githubusercontent.com/assets/2068077/8270709/7e97dab8-17a3-11e5-970b-e8449b5418d6.gif)

**Comment by albert12132** [comment]
We tried with Robert, Jeffrey, and my accounts, all of which are enrolled
in the summer 61A course. I just tried again, and it's still not working.

**Comment by albert12132** [comment]
Ah, my mistake. I forgot I had changed the group size limit. A more descriptive error message on the frontend would be nice.

**Comment by alvinwan** [comment]
@albert12132 Acknowledged.

**Comment by Sumukh** [comment]
In the old frontend - we didn't display the invite field on individual assignments. I think that would be a good solution here.

**Comment by alvinwan** [comment]
Good idea. How do I check group size limit?

**Comment by Sumukh** [comment]
It’s a property of the assignment called max_group_size

max_group_size: 1

-- 
Sumukh Sridhara

On June 20, 2015 at 11:43:30 PM, Alvin Wan (notifications@github.com) wrote:

Good idea. How do I check group size limit?

**Comment by alvinwan** [comment]
Individual assignments no longer show invite option, and the maximum group size is now shown on the invitation form.

![screen shot 2015-06-21 at 12 23 35 am](https://cloud.githubusercontent.com/assets/2068077/8270834/e92a8e90-17ab-11e5-9240-ad549f70390b.png)
