### ISSUE TITLE
Lock date in assignment creation cannot be updated

### ISSUE THREAD

**Issue by albert12132** [Cal-CS-61A-Staff/ok#471]
Changes to the lock date when editing an assignment are not saved.

**Comment by albert12132** [comment]
Has this been deployed? It doesn't seem to work yet.

**Comment by alvinwan** [comment]
Hasn't been deployed yet. I just checked, and the latest version of master fixes this.

**Comment by albert12132** [comment]
Awesome, thanks. Just wanted to double check.

**Comment by papajohn** [comment]
Are we waiting on more changes to deploy?

**Comment by alvinwan** [comment]
Nothing that I know of; unless Soumya and/or Sumukh have something to add, we're ready to deploy.

Aside from #474 (listing courses twice) and #464 (responsive issue on mobile screens), there isn't anything that students can see.

**Comment by soumyabasu** [comment]
There's nothing from my end. @Sumukh?

**Comment by Sumukh** [comment]
I've deployed the master branch (as of 50a5e5eb2e2586d874bda4929c562d38efd909f1)
