### ISSUE TITLE
Courses show up twice on student view

### ISSUE THREAD

**Issue by albert12132** [Cal-CS-61A-Staff/ok#474]
It seems like each course is showing up twice.

![screen shot 2015-06-21 at 7 47 10 pm](https://cloud.githubusercontent.com/assets/2187524/8274861/891a4b96-184e-11e5-9663-f7959b6aa2be.png)

**Comment by alvinwan** [comment]
Investigating now.

**Comment by alvinwan** [comment]
@albert12132 Is it possible that you were enrolled twice in a course? I'm unable to reproduce the error, and my account with the deployed version doesn't have problems. It'd still be a bug, but at least I'd know what to fix.

**Comment by papajohn** [comment]
Maybe because he's both staff and a student (at least he appears on both
the staff and student lists of the currently deployed version)

**Comment by alvinwan** [comment]
Ohh, that's probably it. Thanks.

**Comment by robhuang** [comment]
John's correct. Removing Albert as a student fixed it.
