### ISSUE TITLE
Assignment is incorrectly reported as "late" when submitting

### ISSUE THREAD

**Issue by albert12132** [Cal-CS-61A-Staff/ok#477]
For 61A, we have an assignment `hw01` whose due date is Thursday and lock date is 6/30. However, when running `ok-client` with `--submit`, the client gets a 403 response claiming the submission was "late."

Possibly related; the lock date used to be set to Monday (today) mistakenly, but it was changed yesterday to 6/30.

**Comment by soumyabasu** [comment]
I think it was a caching issue then. I cleared the cache. Try again?

**Comment by albert12132** [comment]
Awesome, it works now. Thanks!
