### ISSUE TITLE
Submission search can't search for multi-word assignment names.

### ISSUE THREAD

**Issue by albert12132** [Cal-CS-61A-Staff/ok#478]
None of the following queries work:

* -assignment "Homework 1"
* -assignment Homework 1
* -assignment --eq "Homework 1"

**Comment by alvinwan** [comment]
Taking a look. Has to do with the regex match.

**Comment by albert12132** [comment]
Is there a particular format for querying multi-word arguments? I tried `-assignment "Homework 1"` again and it still doesn't work. The commit that fixes this issue shows up on Github as having 0 additions and 0 deletions.

**Comment by alvinwan** [comment]
Fix (should be) here: https://github.com/Cal-CS-61A-Staff/ok/commit/a129e2735b79c36411d5cc1a2a961962b184d15f

I'll reopen this for now, and check it out again. The query you have should work.

**Comment by albert12132** [comment]
Hmm. You're right, that regex should work. Is the query being escaped when it gets sent to the server?

**Comment by alvinwan** [comment]
It works. The latest version just hasn't been deployed yet:

![screen shot 2015-06-25 at 4 17 23 pm](https://cloud.githubusercontent.com/assets/2068077/8367688/b0f82872-1b55-11e5-84a9-18e9dce3a206.png)

**Comment by alvinwan** [comment]
@albert12132 Mhm. I believe the existing framework encodes it and decodes it as needed.

**Comment by albert12132** [comment]
Will this be deployed soon?

**Comment by alvinwan** [comment]
You'd have to ask the one and only @Sumukh.

**Comment by Sumukh** [comment]
I'll deploy whatever is on master now - as soon as tests pass.
