### ISSUE TITLE
OK doesn't run correctly on Python 3.5

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/ok#479]
Some context:

Update on "CERTIFICATE_VERIFY" errors

it turns out the student was using a beta version of Python3.5

if a student runs into errors that look like "ERROR_CONNECTION_..." or "TypeError: int + Nonetype", check to see if they're using Python3.4. If they aren't, have them install Python3.4 and see what happens

**Comment by albert12132** [comment]
This also occurs if the the student has a 32-bit version of python3.4.
Having them reinstall a 64-bit version seems to fix the issue.

**Comment by papajohn** [comment]
Thanks, Albert. Although we have a re-install fix, I think it's worth changing the codebase to work with all versions of Python if we can.

**Comment by alvinwan** [comment]
Do we have a traceback for the error(s)? I can take a look.
