### ISSUE TITLE
CSV export for autograded scores

### ISSUE THREAD

**Issue by albert12132** [Cal-CS-61A-Staff/ok#484]

**Comment by Sumukh** [comment]
I tried to export scores from an assignment and Google App Engine cut the process off (it exceeded the timeout of 60 seconds). 

Perhaps we should perform this as a deferred task (https://cloud.google.com/appengine/articles/deferred)  and store/email the CSV somewhere (but probably not in the database)

cc: @LuiseV @alvinwan

**Comment by LuiseV** [comment]
Yeah, I see how that could take too long. I'm without my laptop for the weekend, but can check out the deferred library when I get home, and then work on the issue

**Comment by alvinwan** [comment]
Mhm. This could be a problem for queue generation and zip-file downloads too. I'll take a look.

Convert to deferred task:
- [ ] query download zip
- [ ] queue generation

**Comment by papajohn** [comment]
You could just write it to Google Cloud Storage when someone asks for the
CSV, then provide a download link when it's ready.

https://cloud.google.com/appengine/docs/python/googlecloudstorageclient/

**Comment by alvinwan** [comment]
@LuiseV The Google Cloud Storage API will require a bucket name; you can use `2015_backup`. Just created it.

**Comment by LuiseV** [comment]
Thanks, @alvinwan .

**Comment by LuiseV** [comment]
@alvinwan Do I have access to the bucket? I get "Failed to load" when I try to access it through https://console.developers.google.com/storage/2015_backup/. Is there a different way for me to access it? Or can you give me access for testing purposes?

**Comment by Sumukh** [comment]
@LuiseV - I added your berkeley email to a new bucket created for grades (ok_grade_bucket)

 https://console.developers.google.com/project/ok-server/storage/browser/ok_grades_bucket/

-- 
Sumukh Sridhara

On July 9, 2015 at 6:37:41 PM, LuiseV (notifications@github.com) wrote:

@alvinwan Do I have access to the bucket? I get "Failed to load" when I try to access it through https://console.developers.google.com/storage/2015_backup/. Is there a different way for me to access it? Or can you give me access for testing purposes?

**Comment by LuiseV** [comment]
Thanks, @Sumukh !

**Comment by LuiseV** [comment]
@Sumukh , it says I don't have sufficient permissions to view the page when I follow your link. I am logged in with by Berkeley email.

**Comment by Sumukh** [comment]
whoops - this link should work 

https://console.developers.google.com/storage/browser/ok_grades_bucket 

-- 
Sumukh Sridhara

On July 9, 2015 at 6:51:12 PM, LuiseV (notifications@github.com) wrote:

@Sumukh , it says I don't have sufficient permissions to view the page when I follow your link. I am logged in with by Berkeley email.

**Comment by LuiseV** [comment]
@Sumukh, that works! Thanks

**Comment by alvinwan** [comment]
@LuiseV Sorry, I was afk. Feel free to PM or email me if you need anything else.

**Comment by LuiseV** [comment]
@Sumukh @albert12132 @alvinwan on my branch bug/LuiseV/scoreexport, I now write scores to a cloudstorage file as a deferred task. As long as the files are written in developer mode, they won't show up in our actual GCS bucket. I can access them through the developer link though, so I assume this part will work in the actual app as well.

I have one question: Currently, when I click "download", I am redirected to a site that simply says: 
{
  "data": null, 
  "message": "success", 
  "status": 200
}
The URL is still the one from the score download API call.  I can't figure out if this redirection will also happen in the real app, or only in developer mode. If it is persistent, it should be handled in some other way of course. Probably just a popup window that says/links to where the file can be found in GCS - or something similar. 
Do you know why the above message shows in the browser, and how I can avoid it? Thanks!

**Comment by alvinwan** [comment]
The above is the standard API response. Before, we had to have the user directly cal the API to download a file. Now, because the user is no longer downloading a file and is only sending a command, it'll be easier to make an API endpoint and call it. The API will then trigger the export/deferred task, and the front-end will prompt the user with some kind of link.
