### ISSUE TITLE
Sorting search results only sorts those on the current page

### ISSUE THREAD

**Issue by jeffreylu017** [Cal-CS-61A-Staff/ok#486]
When you sort search results, it only sorts the results on the first page, if the results span multiple pages.  This can be misleading since if I were to sort by submission time, the most recent submission may not actually appear as the first result if it's on a different page.

**Comment by alvinwan** [comment]
I can see how it's misleading - I've removed the ability to sort the current page. By default, all submissions are now sorted by time with the most current on top.

**Comment by soumyabasu** [comment]
I think this is a good fix for now, but we should ideally sort search results through all pages. I think there's some way to do this. @moowiz - do you have an idea here?

**Comment by alvinwan** [comment]
I see. If it comes down to it, I can just add an `-orderby` flag.
