### ISSUE TITLE
Student Composition (notice for reply)- email the staff member

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#506]
Instead of a reply button - something that says - notify your staff member with the email above.

**Comment by alvinwan** [comment]
It's probably about time I finished up the notifications branch; this could be a "email + notify" kind of notification.

**Comment by Sumukh** [comment]
Email notifications when your comment is replied to is useful - however, we don't really need it now. Your call. 

If we want to use emails - we should build up some generic email sending code (perhaps in utils) 
https://cloud.google.com/appengine/docs/python/mail/

**Comment by alvinwan** [comment]
I see. Thanks! I can add a "mailto:" link for now, to resolve this issue. I've created a new PR to house this and other ideas.
