### ISSUE TITLE
Use datepicker for assignment editing

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#515]
Thinking about using https://github.com/Baremetrics/calendar but there are alternatives that also have times.

**Comment by alvinwan** [comment]
As ugly as it is, we could use jQuery UI since it's already included: http://jqueryui.com/datepicker/

**Comment by Sumukh** [comment]
I don't think jQuery UI is included on the admin view. That's a good idea but I think I'll just integrate this when we migrate to the newer version of the admin dashboard framework.

**Comment by alvinwan** [comment]
Ohh, even better. Sounds good.

**Comment by knrafto** [comment]
See #785. v2 is no longer being maintained.
