### ISSUE TITLE
Sudo view is broken

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#516]
We have a `/sudo/su/student@email.com` view for administrators. It currently doesn't have all of the required javascript/css in the HTML template (aka still uses the old front-end code). It'd be nice to have that back and running.

**Comment by alvinwan** [comment]
T_____T But this is woooooooork.

Kidding. What's the sudo window supposed to look like/do?

**Comment by Sumukh** [comment]
:grin: I actually posted it as a reminder for me to do it. It is a weird view and I did write it so I'm happy to fix this.  In the future, any updates to the student template should also get synced to the sudo template. 

It's more a less a clone of the student template just with some kind of warning that you are in sudo mode. It allows administrators to view the front-end as if they were that student. 

Here's how it was done for the last front-end 

```
          {% if sudo %}
            <script>
              window.sudo = "{{sudo.admin}}";
            </script>
            <div class="alert active red">
              <p class="alert-info"><b>SUDO:</b> You are viewing as {{ sudo.su }}. Your actions are being logged. </p>
              <div class="close"><a href={{users_link}}><span class="icon-x">+</span></a> </div>
            </div>

          {% endif %}
```

**Comment by alvinwan** [comment]
LOL. :P Sounds good.

I'll burn through whatever other issues I can do, in the meantime.
