### ISSUE TITLE
Backend Reorganization

### ISSUE THREAD

**Issue by soumyabasu** [Cal-CS-61A-Staff/ok#526]
There's a "Code Reorganization" milestone that Alvin made yesterday, and in it, there's a bullet point called "backend cleanup". I just want to be sure that everyone is on the same page about what a "clean backend" means since I'm a little confused myself.

The main point of confusion for me is what goes in the models and what goes in the API. I think originally, for the models, we had a view of a model is an object, so if we have a User object, we can ask it for things and it should know how to do them. For those calls, the API just calls the corresponding User object and things happen. However, there are other calls, such as downloading a CSV, which is in the api.py file.

Now, I think there are three approaches that we can take here:

1) Dumb down the models. The model just contains the fields and the API has all of the intelligence.

2) Make some clear boundary between the models and the API.

3) Put everything in the models- the API should just be calling the corresponding models.

I think the way that the code is designed right now, doing (2) or (3) would be the least amount of change to the codebase. What does everyone else think?

**Comment by papajohn** [comment]
(2) sounds best. All logic that manipulates data should live in `models`.
All logic that parses input or formats output should live in `api`. Before
anyone embarks on significant reorganization, let's discuss what's moving
where.

**Comment by soumyabasu** [comment]
Yeah, I think the first step is to get our test coverage up so that we're fairly certain that our changes don't break anything.

**Comment by alvinwan** [comment]
Sounds good. PR #527 created.

So building off of (2), and Professor DeNero's distinctions:

**Models**
- Need permissions checks
- all basic operations and queries - as a general rule of thumb, api.py should never need to instantiate a `model` object or use the `query` method?

**API**
- define args
- setup file formats (.zip, .csv .etc)
- error handling

What do you guys think? Also, where do you guys think something like the SearchAPI should be placed? It doesn't have an associated model (kind of), but it's definitely logic.

**Comment by alvinwan** [comment]
Added conclusions to `api.py` and `models.py`. Feel free to modify them. I'll be working on tests in the meanwhile.
