### ISSUE TITLE
User/Participant Status Field Issues

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#534]
So it looks like there are some issues with the users status field (and the participant table as well)  which causes problems whenever we use it. 

There were two issues (copied from #533) 

>
A few issues here - 
1) we added a new field to the user lookup process without first having an index for it. 
This caused any submissions or website requests to fail because app engine wasn't able to process the query in the lookup until the index fully generated. 
2) Not all users have a status attribute - (aprox. 50 users right now) so we can't introduce code that assumes all users have a status. For most pre-existing users, status is NULL. I'm not sure where in the process this would be changed for users.

1 is more of a deploy process issue and we can ignore it for this issue. 

The biggest issue is dealing with pre-existing users because they don't get the default status of 'active' automatically applied to their user record and to their participant entry.  

Before, queries with the status field would return no results - checking for `user.status != 'inactive'` would seem to need the field to exist for the user. 

I've removed all of the status checks I could find until we figure this out. 

I can see how this would be something that would work just fine locally (because all records are created when the server starts) and in tests - but not in production.

**Comment by alvinwan** [comment]
That would be my mistake; should've been waited for code review as Soumya said.

I'll work on a long-term solution when I get home.
