### ISSUE TITLE
Duplicated comments for hog composition

### ISSUE THREAD

**Issue by yulinzheng** [Cal-CS-61A-Staff/ok#542]
The same comment gets duplicated 3 times after refreshing the page.

![screen shot 2015-07-12 at 9 16 46 pm](https://cloud.githubusercontent.com/assets/12951967/8642958/704c7140-28e1-11e5-87a7-76d164a48b2c.png)

If one of them is removed, removing the rest will fail.
![screen shot 2015-07-12 at 9 06 33 pm](https://cloud.githubusercontent.com/assets/12951967/8642965/88227698-28e1-11e5-8b12-644534837e15.png)

To solve the problem above is to refresh the page. After that, both the duplicates and the original comment will disappear. However, if you readd the comment and refresh the page, the same thing happens all over again.

This happened for more than one submission. Here's the link to one of them:
https://ok-server.appspot.com/manage#/submission/final/4701740951666688

**Comment by alvinwan** [comment]
Thanks. Will investigate in the morning.

**Comment by alvinwan** [comment]
@albert12132 I'm unable to view the buggy submission because of a permissions error. Could you add me?

**Comment by albert12132** [comment]
I added you our class on okpy.org.

**Comment by Sumukh** [comment]
I've seen this issue a few times myself when commenting - not sure why it happens but it is a little weird. 

I suspect it might be a front end issue.

**Comment by alvinwan** [comment]
Mhm. Saw the error online and got a chance to play with it; going to try and reproduce locally.

**Comment by knrafto** [comment]
v2 is no longer being maintained.
