### ISSUE TITLE
Student "flag for grading" button doesn't work

### ISSUE THREAD

**Issue by albert12132** [Cal-CS-61A-Staff/ok#544]
Not sure if this functionality has been implemented yet, but right now, if I click on the "flag for grading" button, the following error occurs:

![screen shot 2015-07-13 at 1 01 45 am](https://cloud.githubusercontent.com/assets/2187524/8645276/c464d740-28fa-11e5-8fd8-7bbf58eb85b6.png)

**Comment by alvinwan** [comment]
I will investigate. It may be fixed on master, but I'll have to double-check.

**Comment by alvinwan** [comment]
This is fixed on master. It was broken earlier to fix the composition grading queue. (They're tangentially related, but both are now fixed.)

![mark-as-final](https://cloud.githubusercontent.com/assets/2068077/8656186/f5a222b8-294a-11e5-9666-3fe1d6a5631e.gif)

**Comment by Sumukh** [comment]
Deployed.
