### ISSUE TITLE
Partner A/B (re-ordering)

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#547]
I thought we had this feature (drag and drop partner order) but I'm not sure what happened to it. It might have been removed due to some other bug

**Comment by alvinwan** [comment]
Mhm. I tried it locally and couldn't reproduce. Were you unable to drag, or did it error when you attempted to save? Either way, could you include the traceback? I can't really think of anything that would affect this.

**Comment by alvinwan** [comment]
Happens when assignment is past `lock_date` - need a message to clarify this
