### ISSUE TITLE
Search speed issues: num_per_page, n+1

### ISSUE THREAD

**Issue by alvinwan** [Cal-CS-61A-Staff/ok#559]
While investigating #557, I noticed two things:

- [ ] `num_per_page` has no effect
- [ ] looks like there's an n+1 query happening somewhere, per the image below

![screen shot 2015-08-02 at 11 29 09 am](https://cloud.githubusercontent.com/assets/2068077/9027447/f0653d0c-3909-11e5-9c37-9718a4574b20.png)

**Comment by knrafto** [comment]
v2 is no longer being maintained.
