### ISSUE TITLE
Fix error propagation

### ISSUE THREAD

**Issue by alvinwan** [Cal-CS-61A-Staff/ok#561]
Errors do not propagate to front-end; most everything that's not caught results in a mysterious 500, internal server error.

**Comment by Sumukh** [comment]
:+1: In the few places where we display error messages to users - the frontend has to guess what caused the error.

**Comment by Sumukh** [comment]
It seems like errors do now propagate to users thanks to some of your PRs (and it's a much better experience for users) so I'm closing this.
