### ISSUE TITLE
Templates are erased when assignments are edited.

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#571]
Once you edit an assignment on the front end - any templates that exist are deleted. This might be a PUT vs POST issue on the front-end and be a simple fix (or related to sending a template parameter with no contents)

Related to #451 (not having the ability to have template uploading on the front-end)

**Comment by alvinwan** [comment]
I think it's PUTting an empty template. I can check it out sometime over the weekend if you don't have time.

**Comment by Sumukh** [comment]
I've pushed a fix for this.
