### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by brianhou** [Cal-CS-61A-Staff/ok#573]
![screenshot from 2015-08-26 10 58 50](https://cloud.githubusercontent.com/assets/2406919/9501668/74e51770-4be1-11e5-8386-ec4eae81fff1.png)

Can't click on the right sidebar, which seems a bit confusing. Also, the colors seem to change when you refresh? I think that might also be confusing for students, if they think that the status of their submission changed as well.

@austinhle might have additional comments

**Comment by austinhle** [comment]
Yeah, these were my main concerns as well. There doesn't seem to be a
single set color and the right sidebar should not be displayed (slide in)
until the user actually clicks "View details". Overall, it's still
functional, but can be a bit confusing for students.

**Comment by alvinwan** [comment]
@brianhou That's a little bizarre. The sidebar should behave as @austinhle describes, actually. Which browser are you using?

I'll fix the colors.

Chrome and Safari work fine:
![sidebar](https://cloud.githubusercontent.com/assets/2068077/9504157/e0dcc8ca-4bef-11e5-91b3-f1c06089735e.gif)

**Comment by Sumukh** [comment]
@alvinwan I think it's a screen resolution issue - I can replicate it on screen width > ~1600px.

**Comment by alvinwan** [comment]
Oh, I see. Thanks. I think I know what's causing it. I'll get to it after class.

**Comment by alvinwan** [comment]
addressed sidebar issue

**Comment by Sumukh** [comment]
Will deploy this soon. Thanks @alvinwan
