### ISSUE TITLE
User API returns too much data

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#575]
e.g. GET https://ok-server.appspot.com/api/v1/user/knrafto@berkeley.edu?course=5165212546105344&format=json takes around 13s and returns 25kB of data

**Comment by Sumukh** [comment]
:+1: - This would be a big performance win for students. 
Here's the trace from app engine 
![image](https://cloud.githubusercontent.com/assets/882381/9559025/b1e6bb3a-4da1-11e5-8a99-e6bdf3a8bb05.png)

**Comment by knrafto** [comment]
That doesn't seem right, that says it took only 97ms

**Comment by Sumukh** [comment]
Yeah - I was a little surprised. This one is sounds more realistic (Note the 300+ RPCs!) 

![image](https://cloud.githubusercontent.com/assets/882381/9559057/5e11da3e-4da2-11e5-9ff9-a1cffe312804.png)

**Comment by knrafto** [comment]
v2 is no longer being maintained.
