### ISSUE TITLE
View Code on Search for Submissions page sometimes doesn't work

### ISSUE THREAD

**Issue by brianhou** [Cal-CS-61A-Staff/ok#584]
It works when the query is `-assignment "Hog"` but not when it's `-assignment "Hog" -onlyfinal true`.

The download link goes to https://ok-server.appspot.com/api/v1/submission//download, which would seem to indicate that `submission.backup.id` isn't doing what it should?

**Comment by knrafto** [comment]
Fixed. Also, v2 is no longer being maintained.
