### ISSUE TITLE
Syntax highlighting is a little off

### ISSUE THREAD

**Issue by brianhou** [Cal-CS-61A-Staff/ok#585]
highlight.js seems to do some weird things. I'm not sure if it's actually trying to highlight Python -- it seems that the `python` class only shows up on defs.

Also, it seems that various things trigger comment syntax highlighting (i.e. // and %).

Also, docstrings aren't highlighted as strings. Maybe that's because we're hacking in line numbers?

**Comment by knrafto** [comment]
It's probably because each line is highlighted completely independently. Multiline strings therefore won't get highlighted, and the wrong language is auto-detected on some lines.

**Comment by brianhou** [comment]
Yeah, I think that might be necessary because highlight.js doesn't feel like supporting line numbers. (https://highlightjs.readthedocs.org/en/latest/line-numbers.html)

**Comment by knrafto** [comment]
We could use [this function](http://highlightjs.readthedocs.org/en/latest/api.html#highlight-name-value-ignore-illegals-continuation) to feed it one line at a time (and specify the language too)

**Comment by alvinwan** [comment]
alternatively, we could use prism.js which supports an extension for line numbers

**Comment by Sumukh** [comment]
The continuation one that kyle pointed out looks interesting. 

The reason we separate lines is to support comments & line numbering.

**Comment by alvinwan** [comment]
I can try it using kyle's suggestion.

**Comment by knrafto** [comment]
Fixed in v3 server-side rendering. v2 is no longer being maintained.
