### ISSUE TITLE
My Queue shows all queues ever assigned to me, but doesn't show which semester they're from

### ISSUE THREAD

**Issue by brianhou** [Cal-CS-61A-Staff/ok#593]
![screenshot from 2015-09-13 16 56 36](https://cloud.githubusercontent.com/assets/2406919/9839797/6e223d04-5a38-11e5-9508-b4a5d9dbdde6.png)

**Comment by Sumukh** [comment]
This should be fixed by the admin frontend restructure (to handle having multiple classes) - but it's a quick fix that I can add in for now.

**Comment by Sumukh** [comment]
Closing thanks to #594. Thanks @brianhou!
