### ISSUE TITLE
Inconsistent Behavior for Hamburger Menu

### ISSUE THREAD

**Issue by dchunwong** [Cal-CS-61A-Staff/ok#600]
On the current stable versions of Firefox and Chrome when I click the hamburger menu it will frost the rest of the screen. When I click the menu again there are different behaviors depending on the page I'm on:
On the courses page:
 - Nothing will happen 

On a specific course page (in this case 168):
- The frosted effect will slide out but the menu will stay and content stays moved to the side

In both cases I can still interact with the course objects and assignment objects. If this is intended behavior please feel free to close.

**Comment by Sumukh** [comment]
Thanks Dylan. I've also reproduced this on occasion.

**Comment by knrafto** [comment]
v2 is no longer being maintained.
