### ISSUE TITLE
Reduce instance size. 

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#608]
I don't think there's a real reason we need to be using the most powerful instance size that app engine offers. Looking at our memory usage - it's < 100MB so a 256MB (F2) machine should be enough and reduce our costs for instances by 3x. It's not a huge priority but it'd be interesting to see if it makes a performance impact.

**Comment by knrafto** [comment]
Now down to 1 free instance. v2 is no longer being maintained.
