### ISSUE TITLE
Smarter Composition Diff Rendering [PRs Welcome] 

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#616]
GitHub renders diffs well. We should see how we can improve the diff rendering/computation 

Easy fixes: 
- Frontend: if there is a change show the function/class 
- Frontend: Display +/- 3 lines for context around every diff block. 

Moderate Difficulty: 
- Frontend or Backend: Diff computation should block together changes.

It'd be cool if ok also supported an assignment rubric view (even just a link to an html page would be helpful)

**Comment by knrafto** [comment]
Fixed in v3. v2 is no longer being maintained.
