### ISSUE TITLE
Code review comments are duplicated for deleted lines

### ISSUE THREAD

**Issue by jeffreylu017** [Cal-CS-61A-Staff/ok#617]
Comments on lines right underneath deleted lines seem to always cause duplicated comments to appear for each of the deleted lines (may need to refresh for the duplicates to appear).  Deleting any of the comments will cause all of them to be deleted (again, may need to refresh for the comments to disappear).

![screenshot from 2015-11-01 20 58 34](https://cloud.githubusercontent.com/assets/5020290/10874549/5f2adeb8-80db-11e5-9a54-bdacf46e9c27.png)

![screenshot from 2015-11-01 21 03 14](https://cloud.githubusercontent.com/assets/5020290/10874582/0001ce1e-80dc-11e5-9822-49bba047f6b8.png)

![screenshot from 2015-11-01 21 03 18](https://cloud.githubusercontent.com/assets/5020290/10874583/03541194-80dc-11e5-97b3-364bc58e1ad1.png)

**Comment by knrafto** [comment]
v2 is no longer being maintained.
