### ISSUE TITLE
Assignment creation has all courses in dropdown

### ISSUE THREAD

**Issue by brianhou** [Cal-CS-61A-Staff/ok#618]
![screenshot from 2015-11-03 01 20 10](https://cloud.githubusercontent.com/assets/2406919/10904592/515d66ae-81c9-11e5-8c6c-a77f15c5b4ab.png)

My understanding is that this page is only reached from an existing Course page. I think that means that there really shouldn't be a dropdown here at all since we know what Course the assignment is being created for.

**Comment by knrafto** [comment]
Possibly related: #718. v2 is no longer being maintained.
