### ISSUE TITLE
Enrollment API should not have it's own route/behavior. 

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#630]
Was there a reason the enrollment api endpoint is different from the normal APIs and it doesn't go through to_json etc? 

For consistency - this should be standardized with the other api methods.

**Comment by alvinwan** [comment]
I don't remember, exactly, but I can take care of this (after finals, if that's okay)

**Comment by knrafto** [comment]
Should be more consistent in v3. v2 is no longer being maintained.
