### ISSUE TITLE
Courses always need to display the semester

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/ok#631]
E.g., in the path to enrollment, it says 61A but not which semester. I think it would be easy to enroll a student in the wrong offering accidentally.
![screen shot 2015-12-08 at 10 11 38 am](https://cloud.githubusercontent.com/assets/320145/11664039/3b1021c0-9d94-11e5-86e4-ef7e1b3acbc5.png)

**Comment by knrafto** [comment]
Fixed in v3. v2 is no longer being maintained.
