### ISSUE TITLE
V3 Cleanup

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#639]
Let's place nice to fix issues here: 

- [ ] Investigate the use of Vault for secret management.
- [ ] Use names instead of ID numbers in routes
  - Regex Validation of course names and assignment names`[0-9A-Za-z._-/]+`
- [ ] Lock date defaults to due date + 1 day

Optimizations: 
- Admin Enrollment Queries: https://github.com/Cal-CS-61A-Staff/ok/pull/637#discussion_r50058895

**Comment by knrafto** [comment]
Closing in favor of more granular issues
