### ISSUE TITLE
Flag Submission

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#643]
- [x] Frontend code to flag submission (and unflag) 
- [x] Backups model. 

Whenever submissions is a flagged:  Unflag the previously flagged submission.  
When a user joins a group: The user who is joining has their flagged submission unflagged. The group's flag (or lack of) is respected. 
When a user leaves a group: Do nothing. 

Related: #642

**Comment by knrafto** [comment]
Starting model methods (and tests)
