### ISSUE TITLE
Exports

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#664]

**Comment by Sumukh** [comment]
Score Exports already exist. 
Submission exports is not a commonly used feature now that we have autograding. There is also a easy to use script that provides code exports. 

I'm going to remove the 3.1 milestone for this. It'd be nice to have code exports in the web application, but it's not as necessary as some of the other features in this release.

**Comment by Sumukh** [comment]
Submission exports now exist in #1045
