### ISSUE TITLE
Manual submission

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#713]

**Comment by knrafto** [comment]
Should be able to upload
* A zip (e.g. a submission downloaded from OK). Extra files should be ignored (it may be acceptable to just ignore the meta.json).
* A single source file

**Comment by knrafto** [comment]
Resolved in #726

**Comment by Sumukh** [comment]
@choreff reports autograding erroring out on manual submission. It might have to be fixed on the autograder 

This was related to timestamp formats last time - but requires more inspection.

**Comment by knrafto** [comment]
Autograding is fixed now. But, @choreff would like a checkbox to make the submission one day early (for EC points).
