### ISSUE TITLE
Automatically generate assignment names

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#718]
Instead of making staff members enter assignment names in the form, it should always be `course.offering + '/' + display_name.lower().replace(' ', '')`.

**Comment by Sumukh** [comment]
The only reason this taking a while is because I'd like the UI to indicate this as the assignment is being created. 

If displaying the endpoint in the success message after creation is sufficient, this should just be a 4-5 line change.

**Comment by ericmnelson** [comment]
Hey I just joined in here, but to clarify are we looking to autofill the current form element using the naming formula above and them have them be able to change it, or to take that element out and auto-populate it on creation and then tell the user where the assignment was created?

**Comment by Sumukh** [comment]
Either of those is acceptable. As long as the endpoint is easily copy/pasted - I think users won't mind. 

The former is ideal (where the form indicates what the endpoint is going to be) - but it's more difficult and probably not worth it.

**Comment by Sumukh** [comment]
Resolved in #890
