### ISSUE TITLE
JS and CSS assets should not be in git

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#723]
We shouldn't have to copy a JS library into our repo to use it.

Options:
* Fetch all external libraries from CDNs from the client.
* Flask-Assets bundles will fetch the libraries from CDNs the first time the bundle is used. We may need to write a custom webassets resolver: https://webassets.readthedocs.org/en/latest/generic/custom_resolver.html

**Comment by Sumukh** [comment]
For context: 
We decided against bower because introducing a node/npm dependency to run this seemed like overkill. 

I've been searching for a better assets manager - but can seem to find one that meets our needs.
