### ISSUE TITLE
Fixes for 3.0.5

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#740]
Feel free to chime in with fixes for the next release of OK

- [x] If a user only has one course as a student -> just send them to that page.  (edit: Unnecessary)
- [x] Delete button for student enrollment.  (edit: Pushed back, seems unnecessary)
- [x] Change group email subject lines and body. They don't include enough context and might be using the wrong text 
  -  ("decline" the invite when it should be "revoked" the invitation)
  -  If I revoke someone, it shouldn't sound like they rejected the invite. 
- [x] ~~Health Check API~~ (edit: Unnecessary) 
- [x] Catch Email Exceptions (don't just respond with a 500)

Both issues mentioned in the comment below have been fixed

**Comment by brianhou** [comment]
- Editing an assignment template causes an error.

![screen shot 2016-06-20 at 7 33 51 am](https://cloud.githubusercontent.com/assets/2406919/16198077/6823bd66-36b9-11e6-9f1c-9df888c0357d.png)

**Comment by brianhou** [comment]
![screen shot 2016-06-25 at 4 58 42 pm](https://cloud.githubusercontent.com/assets/2406919/16368271/4b6290da-3be1-11e6-8521-5a89ad886e9f.png)

The due date shouldn’t be red if they’ve already submitted
