### ISSUE TITLE
Fixes for 3.0.6

### ISSUE THREAD

**Issue by brianhou** [Cal-CS-61A-Staff/ok#743]
- [x] Roster export CSV columns are in a different order than the batch enroll expects
- [x] Show “number of students with a submission” for each assignment.

**Comment by Sumukh** [comment]
Stats has a new view since it can take a while to get this data (~10s): 

![image](https://cloud.githubusercontent.com/assets/882381/16414825/c5815fd2-3cee-11e6-90f7-2597ae5da9f9.png)

**Comment by Sumukh** [comment]
- [ ] Sentry User Feedback on error pages

**Comment by Sumukh** [comment]
Resolved in #745
