### ISSUE TITLE
Fixes for 3.0.7

### ISSUE THREAD

**Issue by brianhou** [Cal-CS-61A-Staff/ok#748]
- [x] Various js errors in detailed stats page

![screen shot 2016-07-01 at 11 39 46 am](https://cloud.githubusercontent.com/assets/2406919/16547440/b6071212-4122-11e6-8289-5f4d80c7b02a.png)

**Comment by Sumukh** [comment]
Fixed in #749

**Comment by Sumukh** [comment]
Fixed & Deployed
