### ISSUE TITLE
GradingTask allocation algorithm isn't very fair

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#755]
It looks like the work distribution algorithm (for assigning composition queues) isn't very fair in some cases 

`>>> [len(x) for x in list(chunks(range(45), 13))]`
`[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 9]`

`>>> [len(x) for x in list(chunks(range(253), 13))]`
`[19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 25]`

In utils.py

**Comment by knrafto** [comment]
We could use something similar to http://stackoverflow.com/a/9873935:
```python
import math

def chunks(l, n):
    '''Divides l into n many chunks, each containing approximately the
    same number of elements.

    >>> [len(x) for x in chunks(range(45), 13)]
    [4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 3]
    >>> [len(x) for x in chunks(range(253), 13)]
    [20, 19, 20, 19, 20, 19, 20, 19, 20, 19, 20, 19, 19]
    '''
    length = len(l)
    prev_index = 0
    for i in range(1, n + 1):
        index = math.ceil((i / n) * length)
        yield l[prev_index:index]
        prev_index = index
```

**Comment by Sumukh** [comment]
Thanks! That is much better.
