### ISSUE TITLE
Composition Revision

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#757]
- 1) Support for revision mode submissions
- 2) Revision flag/backup id in export
- 3) Link to revision in original queue for grading 

1 & 2 are required. 3 is optional (unless I hear otherwise)

**Comment by knrafto** [comment]
Revisions have always been really buggy in the past, so maybe we should rethink about how we do them. I'm not sure a separate DB column to mark a revision is worth the added complexity.

Would it be possible to represent them as simply a "Revision: " score tag on a submission instead? They could be tagged by the autograder that searches for submissions after a certain date, or by an API endpoint (though that feels more hacky). That way the revision scores will be in the export automatically.

**Comment by Sumukh** [comment]
Not shoehorning revisions into submissions is a good idea.

How's this: 
- API endpoint `/api/v3/revisions` for revisions that OK Client uses (like `ok --submit` - maybe `ok --revise`?)
  - Reject revisions if not enabled or past revision due date 
  - Maybe: Add a score to the underlying backup, archive revision scores for older revisions
  - Stores entry in Revisions table with `id, timestamp, backup_id` (everything else is accessible through the backup_id... so this table could just have 3 columns) 
- Revisions are stored as backups (as in the api does everything `/api/v3/backups/` does)

**Comment by knrafto** [comment]
(Side note: what does it mean to archive a score?)

Why do we need a Revisions table at all? The scores will already appear in the export, and we could query to see if any submission has a revision score the same way we get assignment scores.

**Comment by Sumukh** [comment]
re: Archiving Score: It's a soft-delete. While technically still in the database, it's not used in the web app (yet). I think there's some value to keeping a historical log of scores (in case we want to do a max of all scores eventually or need to manually restore old scores) 

The main reason you'd want a revisions table is to have an easy query to see if someone has a revision. (though I realized that the schema presented above does not make it easier, we'd want to add submitter_id) - I wanted to avoid a messy query but it looks like SQLAlchemy will make it pretty easy to write: 

```
Backup.options(db.joinedLoad("scores"))
             .query.filter(Backup.scores.any(kind="revision"),
                                  Backup.submitter_id.in(members),
                                  Backup.assignment_id = assignment_id))
             .all()
```

(though there might be a better query that I'm not thinking of)

- [ ] Should revisions be stored with submit: true?  The answer seems to be no. While it makes the revision query faster - it could mean the revision might be detected as the Final Submission if the student doesn't have a flagged submission. (since it's the latest submission) 

This seems workable. Target for this launch is after this weekend.

**Comment by knrafto** [comment]
+1 for revisions being plain backups, not submissions.
