### ISSUE TITLE
Only root level files in backups can be downloaded

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#759]
Downloading a file with the name `tests/hof.py` results in a 404. 

It looks like a routing problem in the download route.

**Comment by knrafto** [comment]
It might be as simple as 's/<file>/<file:path>/' at https://github.com/Cal-CS-61A-Staff/ok/blob/master/server/controllers/student.py#L154

See http://flask.pocoo.org/snippets/76/
