### ISSUE TITLE
Download Button doesn't appear on code with long lines

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#764]
![image](https://cloud.githubusercontent.com/assets/882381/17129117/1145d03c-52c6-11e6-9855-39abb24e3e2b.png)

There should be a download button, but the fact that the table is responsive/has horizontal scroll moves the button of the screen. 

Solution:
Make the header not be part of the responsive table.

**Comment by knrafto** [comment]
What happens to the text of the long lines? Maybe we can get it to wrap at the right length so it doesn't expand the table?

**Comment by Sumukh** [comment]
@knrafto: You can look at an example here https://ok.cs61a.org/cal/cs61a/su16/proj03/submissions/dBN2yk/

GitHub decided to do soft wrapping for text (not code) https://github.com/blog/1707-soft-wrapping-on-prose-diffs 

Before:
![image](https://cloud.githubusercontent.com/assets/882381/17130592/25b1d5f4-52ce-11e6-8d7a-ea8aaec33e1f.png)

After:
![image](https://cloud.githubusercontent.com/assets/882381/17130466/785e90fe-52cd-11e6-9c7c-cf24b01948ae.png)


```
 .highlight-source {
    color: inherit;
-   white-space: pre;
+   white-space: pre-wrap !important;
+   word-break: break-all !important;
+   overflow-wrap: break-word !important;
+   display: block !important;
 }
```
CSS from: https://github.com/StylishThemes/GitHub-code-wrap/blob/master/github-code-wrap.css

This solves some usability problems: 
 - Lack of visibility about horizontal scrolling
 - The download button 


Another option is to have a fixed height - with vertical scroll: 
![image](https://cloud.githubusercontent.com/assets/882381/17130637/69edd16e-52ce-11e6-8fb9-b97b6fbf7b71.png)

**Comment by knrafto** [comment]
The "after" looks alright, though the line number "12" would ideally be aligned with the first line of text
