### ISSUE TITLE
Better search for users

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#770]
e.g. by partial email, SID, or secondary login. Instant filtering would be nice.

**Comment by Sumukh** [comment]
+1

I want to avoid server side search if possible - if we can return 1500 enrollment records in a reasonable time - we should do client side search (which enables instant filtering)  

I'd like to do this without writing spaghetti jQuery code. 

Options: 
- http://www.listjs.com/
- use a JS library (Vue.js) and its extensions (Seems like overkill for this, even though we'll be using Vue.js elsewhere)
