### ISSUE TITLE
Migrate to the okpy.org domain

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#786]
We can do this once the summer semester is over. 

Requirements:
- [x] Get the Kubernetes config ready for the change. (if possible, allow both domains for a short period of time) 
- [x] Add okpy.org to authorized Google Auth domains
- [x] Change the DNS records.

**Comment by Sumukh** [comment]
Completed on the server side. Once the client side moves off ok.cs61a.org, we can make that URL redirect. We still have a week to do so before the SSL cert expires.

**Comment by knrafto** [comment]
What about the redirect ok.cs61a.org -> okpy.org?

**Comment by Sumukh** [comment]
Completed the redirect.
