### ISSUE TITLE
Sudo Mode Improvements 

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#787]
1. Exiting sudo mode should take you back to your account. 

Currently sudo actually replaces your current login - so when you are done you have logout and login again as an admin.  

Logging out while in sudo mode should return you to the admin account you were in. 

Ideally the login link text would indicate "Exit sudo mode", but that's not a must have. 

Implementation wise this easy enough to add, but I want to make sure it's secure. 

```
def logout():
  # logout behavior
  if session['sudo-user']: 
     login(User.get_by_email(session['sudo-user']))
     return redirect('admin.index') 
  return redirect('index') 
```

2. sudo logins should be logged. 

New Table? A generic event log might be useful. 

3.  Use a form for entering sudo mode. 

Not really required, but probably a better experience than having a secret URL.

**Comment by knrafto** [comment]
We shouldn't have sudo mode at all: we'd be able to just use the admin interface to do whatever we need. I view sudo mode as a temporary workaround while we whip the admin interface into shape, so I wouldn't prioritize it.
