### ISSUE TITLE
Single sign-on

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#794]
Many apps use the OK api, and you currently have to remember to use the right Google email for all of them. This is very easy and to mess up. Instead, they should only have to log in through OK.

Apps that could use this:
* ok web interface
* ok-client
* office hours queue
* collaborative editor
* lab assistant manager

**Comment by Sumukh** [comment]
Update - almost done with it - I'm just making small tweaks now. I'll file a PR soon.
