### ISSUE TITLE
Total number of staff members is incorrect

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#809]
On the enrollment page, the "Total: " at the bottom should be the number of staff members, but it looks like it's the number of students.

**Comment by kevinlin1** [comment]
Problem seems to be on [line 66 of students.list.html](https://github.com/Cal-CS-61A-Staff/ok/blob/e41bba890c1265953f8d2b5bd0816e855f43e4dc/server/templates/staff/course/students.list.html#L66). It should not be hardcoded to `enrollments` but rather use the `roster` variable defined in [enrollment.html](https://github.com/Cal-CS-61A-Staff/ok/blob/master/server/templates/staff/course/enrollment.html).
