### ISSUE TITLE
Trigger autograding for a single submission

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#811]
It'd be useful to be able to run autograding for a single (or just a few) backups. 

One approach is to create a new route & a form with parent class being the existing autograding form. 

Potential route:
`/admin/course/assignments/2/autograde/single?ids=ax72b,bx73a` 

Things to look at/change:
- `server/templates/staff/grading/*.html`
- `server/forms.py` 
- `server/controllers/admin.py` (Search for autograding)

**Comment by gratimax** [comment]
I'll try taking this!

**Comment by gratimax** [comment]
I didn't have enough time to finish this soon, I'll unassign myself for someone else to take over it

**Comment by eurieoh** [comment]
I'll try doing this!

**Comment by eurieoh** [comment]
I'm really really sorry, but I'm going to have to unassign myself from this. My computer has kinda been freaking out the past couple of days and I'm going to have to send it in to get it fixed. Since I won't be able to finish this anytime soon, if anyone else wants to claim this, please feel free!

**Comment by knrafto** [comment]
Rather than copying submission IDs, another way would be to have a button on the grading view that will run the autograder. Perhaps limit this button to >= staff only, so it won't interfere with composition grading.
