### ISSUE TITLE
Some python clients do not have the correct certificates installed

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#812]
Setup our cloud balancer to present a full SSL cert if we continue to use LetsEncrypt. Otherwise, some python clients on windows can't verify the cert. 

See comments on the accepted answer here: http://stackoverflow.com/questions/34812787/python-ssl-requests-and-lets-encrypt-certs

Cloud Load Balancer setup https://cloud.google.com/compute/docs/load-balancing/http/ssl-certificates + Kubernetes config. 

If we implement #786 - this issue should just resolve itself.

**Comment by knrafto** [comment]
After migrating, we should grab students who had this issue and test the new version.

**Comment by Sumukh** [comment]
Resolved with okpy.org + using requests in OK Client.
