### ISSUE TITLE
Add ability to un-enroll a student

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#813]
I accidentally enrolled someone in Summer 2016. Not a big deal, but it would be nice to unenroll them.

It could also be useful if we accidentally enroll someone as a staff member and need to revoke access. This could be done by re-enrolling them as a student, but I haven't tried that.

**Comment by Sumukh** [comment]
Potential Approach:
Route that accepts a POST and deletes the enrollment. 
Hookup a delete button column in the list that submits a form to that endpoint

Things to look at:
controllers/admin.py
templates/staff/enrollment/student.list.html
CSRFForm
