### ISSUE TITLE
Canvas API score uploading

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#821]
When scores are updated, they should automatically be pushed to bCourses if they change. Challenges:
- Some students are enrolled under a different email. We should match students based on student ID instead of email.
- We need to configure which scores get sent. Probably some mapping (OK assignment, score kind) -> bCourses assignment.
- Deal with failure somehow - we can't ignore if a score does not get uploaded.

**Comment by knrafto** [comment]
For a first pass, it would be sufficient to have a button on the assignment page that will attempt to export all scores to bCourses (if they change).

We have a repo with scripts to upload scores to bCourses already, which should make this a little easier. For reference, here are the [Canvas API docs](https://bcourses.berkeley.edu/doc/api/submissions.html#method.submissions_api.bulk_update) for grades.

Testing this might be hard. We should mock the API requests/responses for our tests. Testing in production should be done ASAP, before we make the bCourses course public.

**Comment by Rohit-L** [comment]
Will take a look into this.

**Comment by Rohit-L** [comment]
Is it okay if this is only supported for CS61A right now?

**Comment by Sumukh** [comment]
I think it should be generic enough for any course to use it - bCourses will be used for multiple courses next semester. 

This semester three courses (at Berkeley) are using Ok. 

What part of it is harder when we have multiple courses?

**Comment by Rohit-L** [comment]
It's definitely doable. We will need to store the bCourse course id and assignment ids with ok. Any recommendations on the best way to do that? Looking at the scripts that were used for uploading before, it seems they were hardcoded.

**Comment by knrafto** [comment]
See Slack (#ok-server)

**Comment by knrafto** [comment]
Resolved by #986
