### ISSUE TITLE
Comment previews do not work

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#823]
How to reproduce:

* Find a submission
* Type in a comment
* Hit the "Preview" tab
* Look at all the JS errors

We should probably add a test.

**Comment by Sumukh** [comment]
While we are at it - can we add realtime previews for markdown? Not necessary but I figured this would be a good place to mention. 

Vue.js will make it really easy to have live markdown preview (which I think is better for staff who aren't aware how markdown makes their comments look?) 

Last I checked, the vue.js source is also smaller than our existing markdown JS library. 

All the JS we need
```
<div id="editor">
  <textarea v-model="input" debounce="300"></textarea>
  <div v-html="input | marked"></div>
</div>
```
```
new Vue({
  el: '#editor',
  data: {
    input: '# hello'
  },
  filters: {
    marked: marked
  }
})
```

Result: https://jsfiddle.net/yyx990803/oe7axeab/?utm_source=website&utm_medium=embed&utm_campaign=oe7axeab

**Comment by Sumukh** [comment]
Update: I tried integrating Vue - it wasn't as simple as I hoped. So we'll just avoid databinding for now. 

8dacaa0 resolves this issue for now.  It only affected the student view.

**Comment by knrafto** [comment]
Seems like a hacky fix. I'd like to keep this open so I can look into it later

**Comment by knrafto** [comment]
Closing in favor of making a different issue
