### ISSUE TITLE
Edit/delete OAuth clients

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#827]
Right now you can only create them.

**Comment by Sumukh** [comment]
To contribute: 

Relevant files: 
server/forms.py
server/controller/admin.py  (search for OAuth) 
server/models.py (search for Client class) 

Relevant admin route once installed: 
localhost:5000/admin/clients/ 

What this might look like: 
Clicking on a client from the page above takes you to a detail page with a form that allows you to edit values. 

Bonus points: Allow users to generate a new secret if they lose access to the first one.

**Comment by dip-kush** [comment]
I would like to take this up.

**Comment by Sumukh** [comment]
Sure! Consider yourself assigned to this issue.
