### ISSUE TITLE
Staff should be encouraged to upload templates for assignments

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#828]
It's useful to easily see what the student has changed, so you can skip to the important bits.

**Comment by Sumukh** [comment]
We do this by default for composition grading. 

If we have templates for the assignment, we certainly should render a diff by default unless the user explicitly asks for the full view.

**Comment by Sumukh** [comment]
Also a related issue: The current UI doesn't encourage uploading templates when creating an assignment. You kind of have to hunt for it. 

Maybe we redirect staff to the template upload page after they create an assignment

**Comment by knrafto** [comment]
Yes, I think that's the root issue here - cs61a assignments don't have diffs.

**Comment by knrafto** [comment]
One issue: when the assignment is created, the starter files may not be finalized yet. Maybe we should only do this when a staff member makes the assignment visible?

**Comment by Sumukh** [comment]
Fixed by @eurieoh in #841
