### ISSUE TITLE
Flagging a submission unflags submissions on other assignments

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#832]
Reported by @stanfieldchu:

If you manually flag an submission in lab00, then flag another in hw1, the flag in lab00 will be reset.

**Comment by Sumukh** [comment]
Confirmed. 

How strange. Current guess: the unflag_all is being too aggressive.

**Comment by Sumukh** [comment]
Found. It was `_unflag_all` being too aggressive.  

Will fix and add a test.
