### ISSUE TITLE
Staff submissions for students should not be marked late by autograder

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#842]
Additionally, there should be an option to get the 1-day early EC point.

~~The simple solution is to have an option to set the `created` time (with nice defaults) when staff members submit.~~

**Comment by knrafto** [comment]
Instead of playing with the submission time, I think a better solution is a separate column that tracks whether a backup is "late". Then the submission time is still preserved. It's a little more involved to implement and would required autograder changes though

**Comment by Sumukh** [comment]
Was it you that suggested having Ok just kept track of late penalties? That might be interesting. 

re your comment: We technically have the is_late field already - we would just have to implement the custom assignment extensions table. On a staff submission, an extension could be automatically granted.

**Comment by knrafto** [comment]
Do we need extensions? I was thinking we just have staff submissions not mark it as late (or you could manually toggle it for a student submission) so the autograder treats it normally.

**Comment by knrafto** [comment]
I don't think OK should keep track of the penalties per se, but rather that the autograder uses that information instead of the submission time to apply the penalty.

**Comment by knrafto** [comment]
Okay, I think we've settled on a design:

* [ ] Backups have another time field for their true submission time. It can be NULL, which means we use the "created" time instead.
* [ ] When a staff member submits online, they should have the option to set this. Common options:
  * Now (default; sets submission time to NULL)
  * At deadline (just on time)
  * One day early (for EC point)
  * Custom time
* [ ] We should be able to modify this time, using the options above. This can be done in the grading view (https://okpy.org/admin/grading/xxxxxx)
* [ ] The autograder should pass this info to the scoring script.

**Comment by Sumukh** [comment]
:+1: I think this is good. I can change the autograder once the PR is merged.
