### ISSUE TITLE
Status Dashboard

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#843]
It's more important now to have a publically accessible status dashboard to show the status of OK (and other related services). 

I don't think it can be hosted on our Dokku deployment (because it might need to monitor that site). 

I think it's ok if we spin up a small single purpose server for this. Good practice would be to not host this on the Google Cloud (at the very least in an alternate region? `us-west1` would be a good alternative)

I'm planning on using Cachet (https://cachethq.io/) with cachet-monitor. I don't know of any better open source/free status dashboards.

**Comment by colinschoen** [comment]
Cachet looks good. If you want another option to look at I have used Staytus before too: http://staytus.co

**Comment by Sumukh** [comment]
Good enough for now: http://status.cs61a.org
