### ISSUE TITLE
Way of viewing full score tag. 

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#850]
It'd be useful to see the full contents of a score tag.
![image](https://cloud.githubusercontent.com/assets/882381/18497290/d0cc06b4-79e1-11e6-9241-5df6561a0dd4.png)

Simple implementation that'd be fine for now: These link to a page that outputs the full details. 

Route: `/admin/grading/<backup_id>/score/<score_id>` 

Files to look at: 
`admin.py`
`templates/staff/grading/code.html`

**Comment by knrafto** [comment]
Closed in #908
