### ISSUE TITLE
HTTPS redirection

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#855]
For non-API routes, users should be forced to use HTTPS.

**Comment by knrafto** [comment]
Using Flask-SSLify (#870) didn't quite work, because the Google Cloud load balancer terminates SSL and sends an HTTP request to our app.

One possible approach would be configuring nginx: http://serverfault.com/a/735223
```if ($http_x_forwarded_proto = "http") { return 302 https://$host$request_uri; }``` I'm not sure how to exclude `/api` though.

Perhaps another approach would be to implement this ourselves: if the request has `X-Forwarded-Proto` as http and the route is not `/api`, send a 302 and set the HSTS header. Essentially, just adapt some of [the flask_sslify source](https://github.com/kennethreitz/flask-sslify/blob/master/flask_sslify.py).

**Comment by Sumukh** [comment]
A simple approach for now is to set `PREFERRED_URL_SCHEME = 'https'` in the config so url_for returns https links

**Comment by Sumukh** [comment]
We now redirect _all_ urls to HTTPS (with HSTS)
