### ISSUE TITLE
Add emoji to composition text box.

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#877]
It'd be cool to type in emoji's kind of like how github supports it. `:smile:` -> 😄 

one promising library: 
https://github.com/diy/jquery-emojiarea

**Comment by shivasheeshyadav** [comment]
Hey,
I'm completely new to Open Source and would like to work on this issue.

**Comment by Sumukh** [comment]
@shivasheeshyadav - awesome. This is all yours.  Let us know if you have any questions!

**Comment by shivasheeshyadav** [comment]
Thanks.
So which is the particular file in the codebase which i'll be working on ?

**Comment by Sumukh** [comment]
This issue would touch a lot of files - you'll be adding a javascript library to the page and it would interact with the editor here. 

https://github.com/Cal-CS-61A-Staff/ok/blob/master/server/templates/diff.html

As a good first commit - I'm might suggest tackling #883 first.

**Comment by shivasheeshyadav** [comment]
@Sumukh Ok. I'll tackle #883 first, and then 'll get back to this issue. Thanks for the suggestion.

**Comment by kevinlin1** [comment]
Should be pretty simple with [`markdown-it-emoji`](https://www.npmjs.com/package/markdown-it-emoji).

**Comment by colinschoen** [comment]
Is this WIP? If not I'll take this.

**Comment by colinschoen** [comment]
Not necessary. Closed.
