### ISSUE TITLE
Roles should be displayed differently

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#883]
In drop down menus, we should show more humanized roles:
* staff -> Teaching Assistant
* grader -> Reader
* lab assistant -> Lab Assistant

**Comment by Sumukh** [comment]
Files/Lines to edit: https://github.com/Cal-CS-61A-Staff/ok/blob/master/server/forms.py#L161

**Comment by shivasheeshyadav** [comment]
@knrafto @Sumukh I think i've found the piece of code which needs to edited. I would like to take up this issue and work on it.

**Comment by shivasheeshyadav** [comment]
@knrafto @Sumukh I just made a pull request regarding this issue. But all checks have failed. As I'm new to Open Source, I don't know about these checks. Please help.
