### ISSUE TITLE
Broken link in admin student page

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#891]
There's a little blue square next to the page numbers in the student overview page that looks out of place:
<img width="768" alt="screen shot 2016-10-03 at 8 12 40 pm" src="https://cloud.githubusercontent.com/assets/2042019/19061474/e01081e4-89a5-11e6-9431-b4f248642530.png">

It's a link, and clicking it causes a 500.

**Comment by knrafto** [comment]
That endpoint doesn't even exist in the source. Was this supposed to be a staging deploy that went to prod?

**Comment by Sumukh** [comment]
Yes - I see something that shouldn't be in prod. I'll rollback soon with a new deploy.
