### ISSUE TITLE
Only allow one score per kind

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#898]
If we reautograde, we should overwrite the original score (for that score kind).

**Comment by Sumukh** [comment]
That's what should happen already

**Comment by knrafto** [comment]
It seems to in the UI, but the database still has the old tags

**Comment by Sumukh** [comment]
It does a soft delete on the same backup (using the archived bool)

**Comment by Sumukh** [comment]
I think it's useful to keep that info in the DB - space is cheap

**Comment by knrafto** [comment]
Ah I see. The metabase queries are a little harder to write now, but we can deal with that
