### ISSUE TITLE
Diffs on Admin View are not full width

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#909]
![image](https://cloud.githubusercontent.com/assets/882381/19362558/feb0d5b6-913b-11e6-8431-66b42811044e.png)

The normal code view is fine though.

**Comment by kevinlin1** [comment]
Is this still a problem on the current master?

![screen shot 2016-10-13 at 12 42 39 pm](https://cloud.githubusercontent.com/assets/1915715/19364319/83dad8c6-9142-11e6-8868-acec2d59924a.png)

**Comment by Sumukh** [comment]
Nope. I must have been at looking at it before the deploy completed. Thanks.
