### ISSUE TITLE
Be able to export/store files

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#918]
Some layer of persistent storage for large files would be useful. 

Use cases:
- Download MOSS urls and serve them locally. 
- Serve exports of student code (instead of using scripts)
- Jobs could store files and provide the user a download. 

I think the only viable way to do this is to use the cloud storage system (gcloud storage buckets or S3). 

Ideally we would not be too dependent on GCloud specific features for storage. 

Current approach: 
- Create a new table to store exported file metadata: 
  URL to access (or Gcloud ID), Gcloud bucket, Course (nullable), Assignment (nullable), Creator, Filename, Time Created

Another Idea:
- What if exported files were not persistent? Could we store them in a temporary KV store? 
  (not a fan of this - but I thought I'd put it out there)

**Comment by Sumukh** [comment]
Do you think this FileMetadata table should also support files from backups? (FWIW - I don't think so) 

I'm thinking that we want two tables if we support backups having files sent to Google Cloud Storage. 

Another approach is to go for three tables (I think this is overkill) 
- ExternalFile (storing gcloud relevant info) 
- BackupFile -> points to a ExternalFile 
- ExportFile -> points to a ExternalFile

**Comment by Sumukh** [comment]
I've started to implement this and realized it would be best to just have one model with multiple types (`Backup`, `Export`, ...)  - the types will determine the security level.

**Comment by knrafto** [comment]
How would backups that have multiple external files work? Or a mix of external files and ok-client-like text files?
