### ISSUE TITLE
Expand "Submission Information" bar by clicking on bar

### ISSUE THREAD

**Issue by choreff** [Cal-CS-61A-Staff/ok#923]
Currently, if you go to a submission page (ex: http://ok.cs61a.org/admin/grading/eV0jK5), you can only expand the submission information by clicking on the plus on the side.

I think it would be nicer if you could click on the bar itself to expand and collapse.

**Comment by alejandrogarciasalas** [comment]
it seems like the current admin frontend is based on this [admin panel frontend](https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html). It's a modified bootstrap template. There's some classes for collapsing but the default one would add the + and - symbol on the header. A solution for this would require some hacky code or use a modified version of the default bootstrap collapse classes.
