### ISSUE TITLE
Fix QuantifiedCode issues

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#929]
QuantifiedCode has a bunch of code quality suggestions.

It'd be a good idea to address those. 

![image](https://cloud.githubusercontent.com/assets/882381/19587413/0b98ba3c-9713-11e6-8ba8-1bb5133c451e.png)

https://www.quantifiedcode.com/app/project/e6ae811f0c244655b5026e0883ffb8f9

If you are a first time contributor and only want to tackle some of them - that's fine.

**Comment by the-zebulan** [comment]
@Sumukh ,

I'll try to fix a few of these right now.

**Comment by Sumukh** [comment]
Resolved by @the-zebulan in #930

**Comment by Sumukh** [comment]
Nice!

![image](https://cloud.githubusercontent.com/assets/882381/19590369/5b61f566-9726-11e6-87cb-4cd977e59430.png)

![image](https://cloud.githubusercontent.com/assets/882381/19590371/5f9684da-9726-11e6-905a-0a115caf3f03.png)
