### ISSUE TITLE
Display backup IDs with fixed-with text

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#938]
e.g. as `eE9KWe` instead of as eE9KWe. They're reminiscent of commit hashes.

**Comment by kevinlin1** [comment]
Do you prefer `<tt>` tags or `<code>` tags?

![screenshot 2016-11-30 at 3 13 41 pm](https://cloud.githubusercontent.com/assets/1915715/20775441/cf40f848-b70f-11e6-9ced-fa87d5df786f.png) ![screenshot 2016-11-30 at 3 15 31 pm](https://cloud.githubusercontent.com/assets/1915715/20775448/d9712d7e-b70f-11e6-93c9-d0e69923f44f.png)

**Comment by Sumukh** [comment]
I like `<tt>`

**Comment by knrafto** [comment]
Make a jinja macro so we could change it later if necessary?
