### ISSUE TITLE
Binary file uploads

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#941]
Right now our backend doesn't have a good way to store binary files. We have a JSON dict mapping filenames to file contents, where the contents is a JSON (Unicode) string.

One option is store binary file contents as base64-encoded into a string, but we don't have a way of knowing if the original file was binary or not. Perhaps we can determine the binaryness based on the filename.

**Comment by knrafto** [comment]
Related: if we upload a binary file accidentally, we'll get an internal server error. We should catch the error instead.

**Comment by Sumukh** [comment]
What if we keep the files in a cloud storage provider? It'd be an order of magnitude cheaper than storing it in our DB (17 a gig on the DB vs ~2c on DB) and I think it's bad practice to store largish binary files in DBs anyway. 

We should do #918 first.

**Comment by Sumukh** [comment]
A new course has requested this feature for their assignments.

**Comment by Sumukh** [comment]
Resolved in #1024
