### ISSUE TITLE
Add More Indices To Models

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#944]
When I created the models I forgot that MySQL doesn't support partial indexes (but Postgres does). 

We should add some indices to speed up operations. 

```
Backup.submitter_id
Backup.submitter_id, Backup.assignment_id
Score.assignment_id, Score.kind, Score.archived
Enrollment.course_id, Enrollment.role
```

**Comment by knrafto** [comment]
Hmm, I wonder if this is why our stats / final submission queries seem to be getting slower.
