### ISSUE TITLE
Web interface layout prevents accepting partner invitation on some screens sizes

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#956]
https://piazza.com/class/irwl7o7shzu70z?cid=2084

**Comment by knrafto** [comment]
<img width="790" alt="screen shot 2016-10-29 at 4 00 52 pm" src="https://cloud.githubusercontent.com/assets/2042019/19833271/03c40372-9df1-11e6-9fe2-ae97ebadd302.png">

Group action buttons are not visible

**Comment by knrafto** [comment]
Offending commit (now squashed): https://github.com/Cal-CS-61A-Staff/ok/pull/935/commits/b6b6de97aab18bc2f5a731d8d647395dec2ddf00

**Comment by Sumukh** [comment]
I think the best behavior is to make the group table full width as soon as we are not on a `lg` or `xl` size screen. 

If we restore the old behavior the boxes will overlap because of the table.
