### ISSUE TITLE
Display Student Identifier on Backup Page

### ISSUE THREAD

**Issue by colinschoen** [Cal-CS-61A-Staff/ok#964]
There is currently no indication of who owns a submission on the backup page. We should display the student email and/or a link to the student profile in the breadcrumbs. 

<img width="1184" alt="screen shot 2016-11-02 at 4 54 37 pm" src="https://cloud.githubusercontent.com/assets/2927722/19951711/1789adf6-a11d-11e6-9829-209f73d460ab.png">

**Comment by knrafto** [comment]
It's in the "submission information" box. https://github.com/Cal-CS-61A-Staff/ok/pull/961 will expand the box by default, but idk if it's been deployed yet

**Comment by knrafto** [comment]
deploying now

**Comment by knrafto** [comment]
jk, deploying when the kubernetes machines are back up

**Comment by colinschoen** [comment]
Missed, thanks. Closing.
