### ISSUE TITLE
Import enrollment from bCourses

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#987]
If we set up bCourses, we could use `server.canvas.api.get_students` to get a list of students that we can enroll straight from bCourses at the touch of a button (the button should probably go in `server/templates/canvas/index.html`). No more rearranging columns in Excel.

**Comment by Sumukh** [comment]
A natural request from instructors would be probably be to automatically sync enrollment. For now, we could just tell them to hit the button every day or so. 

We'd need some kind of repeated job infrastructure (which it looks we'll need anyway). Should we extend the Job system to allow for certain kinds of job to run on intervals?

**Comment by knrafto** [comment]
#1009 would help

**Comment by knrafto** [comment]
Okay ready for review
<img width="948" alt="screen shot 2017-01-03 at 12 07 26 am" src="https://cloud.githubusercontent.com/assets/2042019/21602431/a50ce0ac-d148-11e6-842d-4adb05cb42cb.png">
