### ISSUE TITLE
Link on staff page for a submission to the student page

### ISSUE THREAD

**Issue by jathak** [Cal-CS-61A-Staff/ok#992]
It'd be nice to have a link on the staff-facing page for a submission (`/admin/grading/<id>`) to the equivalent student page (`/<offering>/<assignment>/submissions/<id>`) for when I want to include a link to a relevant submission when responding to a regrade request.

**Comment by Sumukh** [comment]
Seems reasonable for now. Where's would a good place to put it? 

If we ever get parity on the admin URLs - it would be as simple as removing `/admin/` (and even possibly redirecting students who go a page to an equivalent student URL)

One option: 

Next to the raw button on the file toolbar. 
![image](https://cloud.githubusercontent.com/assets/882381/20703980/a4a0c41c-b5d2-11e6-933b-85bcdcfcffcd.png)


Another option: 
We could toss it in the submission information - though I don't think it warrants a button (or even another row)

**Comment by knrafto** [comment]
Idea for later: we use the same URL (i.e. okpy.org/cal/cs61a/fa16/proj04/submissions/abcdef) for both the staff and student views, and your permission level decides which one you get. That way we can share the URL directly with students. We could use student.okpy.org to force the student view if necessary.

**Comment by knrafto** [comment]
I don't think putting it in the source file header is a good place, because this is a per-submission thing, not a per-file thing. I'm fine with adding another row to submission information like "URL: " or "Student link: " or similar

**Comment by Sumukh** [comment]
This has been requested again by @papajohn 

> When I find somebody's submission in the admin view, I'm never sure how to send them a link to that submission that will work from their student view.
